import React,{useState,useEffect} from 'react';
import {Search, Database, ShieldCheck, ArrowRight, ChevronLeft, ChevronRight, FileJson, Info, ExternalLink, Copy, Download, CheckCheck, Clock3} from 'lucide-react';
import {PageHead,TeamBadge,Status,ExportButton,Empty,Loading,ErrorBanner,Modal,Legend,PATTERNS,useResource,api,num,scoreText,dateLabel,timeLabel} from './shared';

export function ScorePill({kind,code}){return <span className={`score-pill ${code?`code-${kind}-${code}`:'missing'}`}>{code?PATTERNS[kind].labels[code]:'—'}</span>;}
function codes(m){if(m.status!=='final')return {};const total=m.ft_home+m.ft_away;return {parity:total%2?'O':'E',btts:m.ft_home>0&&m.ft_away>0?'Y':'N',dnb:m.ft_home===m.ft_away?'V':m.ft_home>m.ft_away?'W':'L',total:total>=3?'O':'U'};}

export default function Archive({data,onInspect,toast}){
  const [season,setSeason]=useState(data.current_season||data.seasons[0]?.id),[day,setDay]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0);
  const {data:results,error,loading}=useResource(season?`/api/results?season=${season}${day?`&day=${day}`:''}`:null,data.version);
  const rows=results?.matches.filter(m=>`${m.home} ${m.away}`.toLowerCase().includes(search.toLowerCase()))||[],pages=Math.max(1,Math.ceil(rows.length/20));
  const visible=rows.slice(Math.min(page,pages-1)*20,Math.min(page,pages-1)*20+20),summary=data.seasons.find(s=>s.id===Number(season));
  useEffect(()=>setPage(0),[season,day,search]);
  return <><PageHead eyebrow="THE PERSISTENT ARCHIVE" title="Every score. On record." description="Original team names, half-time scores and full-time results. All from Betika."><ExportButton season={season} toast={toast}/></PageHead>
    <div className="archive-summary"><div><Database size={20}/><span><strong>{num(data.counts.finalized)}</strong> finalized matches</span></div><div><ShieldCheck size={20}/><span><strong>{num(data.counts.complete_days)}</strong> verified matchdays</span></div><div><FileJson size={20}/><span><strong>{num(data.counts.receipts)}</strong> source snapshots</span></div><Status tone="green">STORED LOCALLY</Status></div>
    <div className="panel archive-panel"><div className="explorer-toolbar"><div className="filter-group"><label><span>SEASON</span><select value={season||''} aria-label="Results season" onChange={e=>{setSeason(Number(e.target.value));setDay('');}}>{data.seasons.map(s=><option key={s.id} value={s.id}>{s.id}{s.current?' · Current':''}</option>)}</select></label><label><span>MATCHDAY</span><select value={day} aria-label="Results matchday" onChange={e=>setDay(e.target.value)}><option value="">All matchdays</option>{Array.from({length:30},(_,i)=><option key={i} value={i+1}>Matchday {i+1}</option>)}</select></label><label className="search-field"><Search size={16}/><input aria-label="Search results teams" placeholder="Filter by team…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><span className="results-count">{num(rows.length)} records</span></div>
      <div className="season-progress"><div><b>Season {season}</b><span>{summary?.complete_days||0} of 30 days finalized</span></div><div className="day-strip">{summary?.days.map(d=><button title={`Matchday ${d.day} · ${d.status} · ${d.final_count}/8 final`} aria-label={`Filter matchday ${d.day}`} key={d.day} className={`day-box ${d.status} ${Number(day)===d.day?'chosen':''}`} onClick={()=>setDay(Number(day)===d.day?'':String(d.day))}>{String(d.day).padStart(2,'0')}</button>)}</div></div><ErrorBanner error={error}/>
      {loading&&!results?<Loading/>:rows.length?<><div className="archive-table-scroll"><table className="archive-table"><thead><tr><th>MD</th><th className="teams-col">MATCH · HOME / AWAY</th><th>HT</th><th>FT</th><th>ODD / EVEN</th><th>BTTS</th><th title="Draw no bet from the home team's perspective">HOME DNB</th><th>O / U 2.5</th><th>STATUS</th><th/></tr></thead><tbody>{visible.map(m=>{const c=codes(m);return <tr key={m.id}><td><span className="matchday-index">{String(m.day).padStart(2,'0')}</span></td><td><div className="archive-teams"><span><TeamBadge name={m.home} small/>{m.home}</span><small>vs</small><span><TeamBadge name={m.away} small/>{m.away}</span></div></td><td className="score-cell">{scoreText(m.ht_home,m.ht_away)}</td><td className="score-cell ft">{scoreText(m.ft_home,m.ft_away)}</td><td><ScorePill kind="parity" code={c.parity}/></td><td><ScorePill kind="btts" code={c.btts}/></td><td><ScorePill kind="dnb" code={c.dnb}/></td><td><ScorePill kind="total" code={c.total}/></td><td><Status tone={m.status==='final'?'green':m.status==='live'?'amber':'muted'} dot={m.status==='live'}>{m.status==='final'?'Final':m.status==='live'?'Provisional':'Upcoming'}</Status></td><td><button className="icon-button" title="Inspect result & source receipt" aria-label={`Inspect ${m.home} vs ${m.away}`} onClick={()=>onInspect(m.id)}><FileJson size={16}/></button></td></tr>;})}</tbody></table></div><div className="table-pagination"><span>Showing {Math.min(page,pages-1)*20+1}–{Math.min((Math.min(page,pages-1)+1)*20,rows.length)} of {num(rows.length)} matches</span><div><button className="icon-button" disabled={page<=0} onClick={()=>setPage(p=>p-1)} aria-label="Previous results page"><ChevronLeft size={17}/></button><span>Page <b>{Math.min(page,pages-1)+1}</b> of {pages}</span><button className="icon-button" disabled={page>=pages-1} onClick={()=>setPage(p=>p+1)} aria-label="Next results page"><ChevronRight size={17}/></button></div></div></>:<Empty title="No stored results for these filters" description="This matchday may not be played or collected yet. Try another day or clear the team filter."/>}
    </div><div className="notice archive-note"><Info size={18}/><span>Only verified final scores receive pattern labels. Provisional or scheduled fixtures show “—” in HT/FT columns. Open their source receipt to inspect the most recently observed live score. DNB in this table is relative to the <b>home team</b>.</span></div>
  </>;
}

export function ResultInspector({id,onClose,toast}){
  const {data,error,loading}=useResource(`/api/matches/${id}`);const [showRaw,setShowRaw]=useState(false);
  const m=data?.match,hash=m?.final_source_hash||m?.last_source_hash;
  const receipt=useResource(showRaw&&hash?`/api/provenance/${hash}`:null);
  async function copy(){try{await navigator.clipboard.writeText(hash);toast('Source fingerprint copied.');}catch{toast('Copy unavailable in this browser; select the hash below.','error');}}
  return <Modal title="A result you can trace" onClose={onClose}><div className="inspector-body"><ErrorBanner error={error}/>{loading?<Loading/>:m&&<><div className="inspector-meta"><Status tone={m.status==='final'?'green':'amber'}>{m.status==='final'?'FINAL · VERIFIED':'NOT FINAL'}</Status><span>Season {m.season} / Matchday {m.day}</span></div><div className="result-scoreboard"><div><TeamBadge name={m.home}/><h3>{m.home}</h3><small>HOME</small></div><div className="big-result"><strong>{m.status==='final'?scoreText(m.ft_home,m.ft_away):scoreText(m.live_ft_home,m.live_ft_away)}</strong><span>{m.status==='final'?'FULL TIME':'OBSERVED · PROVISIONAL'}</span><small>HT {m.status==='final'?scoreText(m.ht_home,m.ht_away):scoreText(m.live_ht_home,m.live_ht_away)}</small></div><div><TeamBadge name={m.away}/><h3>{m.away}</h3><small>AWAY</small></div></div>{m.status==='final'&&<div className="inspector-patterns">{Object.entries(codes(m)).map(([k,c])=><div key={k}><span>{PATTERNS[k].name}{k==='dnb'?' · home':''}</span><ScorePill kind={k} code={c}/></div>)}</div>}<div className="source-receipt"><h3><ShieldCheck size={18}/>Source receipt</h3><dl><dt>Collected from</dt><dd>Betika public website feed</dd><dt>Local record</dt><dd>#{m.id}{m.event_id?` · Event ${m.event_id}`:''}</dd><dt>First observed</dt><dd>{dateLabel(m.first_seen)}</dd><dt>Last observed</dt><dd>{dateLabel(m.updated_at)}</dd>{m.final_at&&<><dt>Finalized</dt><dd>{dateLabel(m.final_at)}</dd></>}<dt>Source status</dt><dd>{m.source_status||m.status}{m.phase?` / ${m.phase}`:''}</dd></dl><div className="hash-label"><span>SHA-256 · SOURCE PAYLOAD</span><button className="icon-button" onClick={copy} aria-label="Copy receipt hash"><Copy size={14}/></button></div><code className="source-hash">{hash||'Receipt unavailable'}</code></div><button className="button secondary full-width" onClick={()=>setShowRaw(!showRaw)}><FileJson size={16}/>{showRaw?'Hide source payload':'Inspect original source payload'}</button>{showRaw&&<div className="raw-source"><ErrorBanner error={receipt.error}/>{receipt.loading?<Loading text="Reading stored source evidence…"/>:receipt.data&&<><div className="source-url">{receipt.data.url}</div><p>Captured {dateLabel(receipt.data.first_seen)} · HTTP Date: {receipt.data.source_date||'not supplied'}</p><pre>{JSON.stringify(receipt.data.payload,null,2)}</pre></>}</div>}<p className="fine-print">The receipt contains the public response captured by this application. The hash detects payload changes; it is not a cryptographic signature issued by Betika.</p></>}</div></Modal>;
}
