import React,{useEffect,useState} from 'react';
import {ScanLine, SlidersHorizontal, GitCompareArrows, ArrowRight, ChevronLeft, ChevronRight, Bookmark, BookmarkCheck, RefreshCw, Info, Clock3, Trash2, Check, Pause, Radio, X} from 'lucide-react';
import {PageHead,PATTERNS,PatternTabs,Legend,PatternCard,TeamBadge,Status,Loading,Empty,ErrorBanner,Modal,useResource,api,num,dateLabel} from './shared';

export function Alignment({kind,currentTeam,currentSeason,cards,historicalTeam,historicalSeason,historicalCards,start,readOnly=false,onInspect,CardComponent=PatternCard,currentLabel}){
  const end=start+cards.length-1;
  const currentFirst=cards[0]?.day||1,currentLast=cards[cards.length-1]?.day||cards.length;
  return <div className="alignment-scroll"><div className="alignment-canvas"><div className="alignment-ruler"><div className="dna-label">HISTORICAL MATCHDAY <ArrowRight size={12}/></div>{Array.from({length:30},(_,i)=><span key={i}>{String(i+1).padStart(2,'0')}</span>)}</div><div className="alignment-row current-row"><div className="dna-label"><span className="row-kind">{readOnly?'CAPTURED PREFIX':currentLabel||'FORMING PATTERN'}</span><span className="alignment-team"><TeamBadge name={currentTeam} small/><strong>{currentTeam}</strong></span><small>S{currentSeason} · MD {currentFirst}–{currentLast}</small></div>{Array.from({length:30},(_,i)=>{const card=cards[i-start+1];return card?<CardComponent key={i} card={card} kind={kind} onInspect={onInspect} withDay/>:<div className="alignment-blank" key={i}>{i===start+cards.length-1?<span>…</span>:null}</div>;})}</div><div className="alignment-bridge"><div className="dna-label"><GitCompareArrows size={15}/><span>SLIDING ALIGNMENT</span></div><div className="bridge-track" style={{gridColumn:`${start+1} / span ${Math.max(1,cards.length)}`}}><span/><b>MD {String(currentFirst).padStart(2,'0')}–{String(currentLast).padStart(2,'0')} ↔ MD {String(start).padStart(2,'0')}–{String(end).padStart(2,'0')}</b><span/></div></div><div className="alignment-row historical-row"><div className="dna-label"><span className="row-kind archive">HISTORICAL BLUEPRINT</span><span className="alignment-team"><TeamBadge name={historicalTeam} small/><strong>{historicalTeam}</strong></span><small>S{historicalSeason} · MD 1–30</small></div>{historicalCards.map((card,i)=>{const selected=i>=start-1&&i<end;const mismatch=selected&&cards[i-start+1]?.code!==card.code;return <CardComponent key={i} kind={kind} card={card} muted={!selected} withDay onInspect={onInspect} mismatch={mismatch}/>;})}</div></div></div>;
}

export default function Comparator({data,onInspect,toast,onHelp}){
  const [kind,setKind]=useState('parity'),[minimum,setMinimum]=useState(100),[scope,setScope]=useState('all'),[auto,setAuto]=useState(true),[refresh,setRefresh]=useState(0),[selectedTeam,setSelectedTeam]=useState(''),[candidateIndex,setCandidateIndex]=useState(0),[start,setStart]=useState(1),[showPins,setShowPins]=useState(false),[saving,setSaving]=useState(false),[pinVersion,setPinVersion]=useState(0);
  const rev=`${refresh}-${auto?`${data.fp_revision}-${data.current_season}-${data.upcoming.day}`:'frozen'}`;
  const {data:result,error,loading}=useResource(`/api/compare?kind=${kind}&minimum=${minimum}&scope=${scope}`,rev);
  const selected=result?.teams.find(t=>t.team===selectedTeam)||result?.teams.find(t=>t.candidates.length)||result?.teams[0];
  const candidate=selected?.candidates[candidateIndex]||selected?.candidates[0];
  useEffect(()=>{setCandidateIndex(0);},[selectedTeam,kind,scope,minimum]);
  useEffect(()=>{if(candidate)setStart(candidate.start);},[candidate?.team,candidate?.season,candidate?.start,result?.revision]);
  useEffect(()=>{if(result&&(!selectedTeam||!result.teams.some(t=>t.team===selectedTeam)))setSelectedTeam(result.teams.find(t=>t.candidates.length)?.team||result.teams[0]?.team||'');},[result?.teams.map(t=>t.team).join('|')]);
  const matched=candidate?selected.cards.reduce((n,c,i)=>n+(c.code===candidate.cards[start-1+i]?.code?1:0),0):0;
  const similarity=selected?.cards.length?Math.round(matched/selected.cards.length*1000)/10:0;
  async function save(){if(!candidate)return;setSaving(true);try{await api('/api/pins',{method:'POST',body:JSON.stringify({kind,team:selected.team,historical_team:candidate.team,historical_season:candidate.season,start,current_season:result.current_season,length:selected.cards.length,current_signature:selected.prefix})});toast('Alignment pinned. This is a fixed historical snapshot, stored in SQLite.');setPinVersion(v=>v+1);}catch(e){toast(e.message,'error');}finally{setSaving(false);}}
  return <><PageHead eyebrow="THE COMPARISON ENGINE" title="Find the familiar." description="Trace the forming season through earlier blueprints — even when the matchdays differ."><button className="button secondary" onClick={()=>setShowPins(true)}><Bookmark size={16}/>Saved alignments</button></PageHead><PatternTabs kind={kind} onChange={setKind} compact/>
    <div className="comparison-controls panel"><div className="control-label"><SlidersHorizontal size={18}/><span>Compare with</span></div><label><span>Historical teams</span><select value={scope} aria-label="Historical team scope" onChange={e=>setScope(e.target.value)}><option value="all">All teams</option><option value="same">Same team only</option></select></label><label><span>Minimum similarity</span><select value={minimum} aria-label="Minimum similarity" onChange={e=>setMinimum(Number(e.target.value))}><option value="100">Exact match · 100%</option><option value="90">90% or higher</option><option value="80">80% or higher</option><option value="70">70% or higher</option><option value="50">50% or higher</option></select></label><div className="comparison-auto"><button className={`switch ${auto?'on':''}`} role="switch" aria-checked={auto} aria-label="Auto-rematch when results close" onClick={()=>setAuto(!auto)}><i/></button><span>Auto-rematch</span><button className="icon-button" title="Refresh comparison" aria-label="Refresh comparison" onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={16} className={loading?'spin':''}/></button></div></div><ErrorBanner error={error}/>
    <div className="comparison-stats"><div><span className="comparison-stat-icon"><ScanLine size={18}/></span><span><strong>{num(result?.teams.length)}</strong>upcoming teams</span></div><div><span><strong>{num(result?.windows_scanned)}</strong>historical windows checked</span></div><div><span><strong>{num(result?.match_count)}</strong>{minimum===100?'exact alignments':'qualifying alignments'}</span></div><div className="prefix-stat"><Status tone={auto?'green':'amber'}>{auto?'AUTO SYNC':'FROZEN VIEW'}</Status><span>Current prefix <b>MD 01–{String(result?.length||0).padStart(2,'0')}</b></span></div></div>
    {result?.length>0&&result.length<5&&<div className="notice warning"><Info size={17}/><span>This is a short sequence. Exact matches are common by chance and are not evidence of predictive value.</span></div>}
    <section className="team-scan"><div className="section-head"><div className="section-title"><h2>All teams, compared.</h2><span className="subtle-label">S{result?.current_season} / UPCOMING MD {result?.upcoming_day}</span></div><span className="muted-text">Select a team to inspect its alignments</span></div>{loading&&!result?<Loading/>:<div className="team-scan-grid">{result?.teams.map(t=><button className={`team-scan-card ${selected?.team===t.team?'selected':''}`} key={t.team} onClick={()=>{setSelectedTeam(t.team);setCandidateIndex(0);}}><TeamBadge name={t.team} small/><span><strong>{t.team}</strong><small>{t.match_count?`${num(t.match_count)} ${minimum===100?'exact ':''}alignment${t.match_count===1?'':'s'}`:'No matching sequence'}</small></span><span className={`match-count ${t.match_count?'found':''}`}>{t.match_count?<Check size={14}/>:<span>—</span>}</span></button>)}</div>}</section>
    <section className="panel alignment-panel"><div className="alignment-head"><div className="icon-title"><GitCompareArrows size={20}/><div><h2>Alignment workspace</h2><p>One forming sequence. Every possible starting point.</p></div></div>{candidate&&<div className={`similarity-score ${similarity===100?'exact':''}`}><strong>{similarity}<small>%</small></strong><span>SYMBOL<br/>SIMILARITY</span></div>}</div>
      {candidate?<><div className="candidate-toolbar"><div><span className="field-caption">HISTORICAL MATCH</span><select value={Math.min(candidateIndex,selected.candidates.length-1)} aria-label="Choose historical alignment" onChange={e=>setCandidateIndex(Number(e.target.value))}>{selected.candidates.map((c,i)=><option key={`${c.season}-${c.team}-${c.start}`} value={i}>{c.team} · S{c.season} · MD {c.start}–{c.end} · {c.similarity}%</option>)}</select></div><div className="candidate-pager"><span>{Math.min(candidateIndex+1,selected.candidates.length)} / {selected.candidates.length} shown{selected.match_count>20?' · top 20':''}</span><button className="icon-button" disabled={candidateIndex<=0} onClick={()=>setCandidateIndex(i=>i-1)} aria-label="Previous alignment"><ChevronLeft size={17}/></button><button className="icon-button" disabled={candidateIndex>=selected.candidates.length-1} onClick={()=>setCandidateIndex(i=>i+1)} aria-label="Next alignment"><ChevronRight size={17}/></button></div></div><div className="alignment-legend"><Legend kind={kind}/><span><i className="mismatch-key">×</i> Different outcome <i/> Muted cards are context only</span></div>
        <Alignment kind={kind} currentTeam={selected.team} currentSeason={result.current_season} cards={selected.cards} historicalTeam={candidate.team} historicalSeason={candidate.season} historicalCards={candidate.cards} start={start} onInspect={onInspect}/>
        <div className="alignment-controls"><div className="offset-control"><span>Historical start</span><div className="stepper"><button disabled={start<=1} onClick={()=>setStart(s=>s-1)} aria-label="Move historical window back"><ChevronLeft size={15}/></button><b>MD {String(start).padStart(2,'0')}</b><button disabled={start>=31-selected.cards.length} onClick={()=>setStart(s=>s+1)} aria-label="Move historical window forward"><ChevronRight size={15}/></button></div><input type="range" min="1" max={31-selected.cards.length} value={start} aria-label="Historical starting matchday" onChange={e=>setStart(Number(e.target.value))}/><button className="text-button" onClick={()=>setStart(candidate.start)}>Reset alignment</button></div><button className="button primary" onClick={save} disabled={saving}>{saving?<RefreshCw className="spin" size={16}/>:<Bookmark size={16}/>}Pin snapshot</button></div><div className="alignment-result"><span><b>{matched} of {selected.cards.length}</b> symbols match at this offset{matched===selected.cards.length?' · exact alignment':' · not an exact match'}.</span><span>{auto?'Rematches after a finalized matchday':'Auto-rematch paused'}<span className="tiny-dot"/></span></div></>:<Empty title={!result?.length?'Waiting for a complete prefix':`No ${minimum===100?'exact ':'qualifying '}alignment for ${selected?.team||'this team'}`} description={!result?.length?'A forming pattern needs consecutively finalized matchdays starting at MD 1. Live scores and missing days are not used.':`The ${result.length}-matchday sequence does not meet this threshold in the available historical windows. This is a valid result — nothing is fabricated.`} icon={ScanLine}>{minimum===100&&result?.length>0&&<button className="button secondary" onClick={()=>setMinimum(90)}>Inspect 90%+ similarities<ArrowRight size={15}/></button>}</Empty>}
    </section>
    <div className="comparator-foot"><div className="notice"><Info size={19}/><span><strong>Similarity, not certainty.</strong> A matching history does not predict what happens next. The playing matchday is excluded until finalized. <button className="text-button" onClick={onHelp}>Understand the method<ArrowUpIcon/></button></span></div><div className="local-speed"><span className="tiny-dot"/>Computed locally in <b>{result?.compute_ms??'—'} ms</b><span>{result?.cached?'Cached comparison':'Sliding-window scan'}</span></div></div>
    {showPins&&<SavedPins onClose={()=>setShowPins(false)} onInspect={onInspect} toast={toast} version={pinVersion}/>}
  </>;
}
function ArrowUpIcon(){return <ArrowRight size={12}/>;}
function SavedPins({onClose,onInspect,toast,version}){
  const [rev,setRev]=useState(version),[expanded,setExpanded]=useState(null);const {data,error,loading}=useResource('/api/pins',rev);
  async function remove(id){try{await api(`/api/pins/${id}`,{method:'DELETE'});setRev(v=>v+1);toast('Saved alignment removed.');}catch(e){toast(e.message,'error');}}
  return <Modal title="Saved alignments" onClose={onClose} wide><div className="saved-body"><p className="lead">Fixed snapshots from your workspace. Saved results never silently change as the live season advances.</p><ErrorBanner error={error}/>{loading&&!data?<Loading/>:!data?.pins.length?<Empty title="Keep an interesting alignment" description="Use “Pin snapshot” in the comparator. Your selected rows and historical offset are stored in the persistent database." icon={Bookmark}/>:data.pins.map(p=><article className="saved-item" key={p.id}><div className="saved-item-head"><div><Status tone="violet" dot={false}>{PATTERNS[p.kind].name}</Status><h3>{p.team}<span> ↔ </span>{p.historical_team}</h3><p>S{p.current_season} / MD 1–{p.length} · S{p.historical_season} / from MD {p.start} · {p.matched}/{p.length} matching</p><small>Captured {dateLabel(p.created_at)}</small></div><div><button className="button secondary" onClick={()=>setExpanded(expanded===p.id?null:p.id)}>{expanded===p.id?'Collapse':'Inspect'}</button><button className="icon-button danger" aria-label="Delete saved alignment" onClick={()=>remove(p.id)}><Trash2 size={17}/></button></div></div>{expanded===p.id&&<Alignment kind={p.kind} currentTeam={p.team} currentSeason={p.current_season} cards={p.current_cards} historicalTeam={p.historical_team} historicalSeason={p.historical_season} historicalCards={p.historical_cards} start={p.start} readOnly onInspect={onInspect}/>}</article>)}</div></Modal>;
}
