import React,{useState,useEffect} from 'react';
import {Search, Fingerprint, Grid2X2, Rows3, Info, ArrowRight, X, ScanLine} from 'lucide-react';
import {PageHead,PATTERNS,PatternTabs,Legend,PatternCard,TeamBadge,Status,Loading,Empty,ErrorBanner,ExportButton,useResource,num} from './shared';

export default function Explorer({data,initialTeam,onInspect,onNavigate,toast,globalSearch}){
  const [season,setSeason]=useState(data.current_season||data.seasons[0]?.id),[kind,setKind]=useState('parity'),[search,setSearch]=useState(initialTeam||globalSearch||''),[compact,setCompact]=useState(false);
  useEffect(()=>{if(initialTeam)setSearch(initialTeam);},[initialTeam]);
  useEffect(()=>{if(globalSearch||!initialTeam)setSearch(globalSearch||'');},[globalSearch]);
  const {data:fp,error,loading}=useResource(season?`/api/blueprints?season=${season}&kind=${kind}`:null,data.fp_revision);
  const teams=fp?.teams.filter(t=>t.team.toLowerCase().includes(search.toLowerCase()))||[];
  const summary=data.seasons.find(s=>s.id===Number(season));
  const confirmed=fp?.teams.reduce((a,t)=>a+t.played,0)||0;
  return <><PageHead eyebrow="THE FINGERPRINT WORKSPACE" title="A season. A sequence. A story." description="Explore the full-time signature of every team, one matchday at a time."><ExportButton season={season} toast={toast}/></PageHead>
    <PatternTabs kind={kind} onChange={setKind}/>
    <div className="panel explorer-panel"><div className="explorer-toolbar"><div className="filter-group"><label><span>SEASON</span><select aria-label="DNA season" value={season||''} onChange={e=>setSeason(Number(e.target.value))}>{data.seasons.map(s=><option key={s.id} value={s.id}>{s.id}{s.current?' · Current':''}</option>)}</select></label><label className="search-field"><Search size={17}/><input aria-label="Search DNA teams" placeholder="Find a team…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button className="input-clear" aria-label="Clear team search" onClick={()=>setSearch('')}><X size={14}/></button>}</label></div><div className="toolbar-right"><span className="results-count">{teams.length} teams</span><div className="view-switch icon-switch"><button className={!compact?'active':''} aria-label="Score cards" title="Score cards" onClick={()=>setCompact(false)}><Grid2X2 size={16}/></button><button className={compact?'active':''} aria-label="Compact patterns" title="Compact patterns" onClick={()=>setCompact(true)}><Rows3 size={16}/></button></div></div></div>
      <div className="blueprint-heading"><div><span className="blueprint-number">{PATTERNS[kind].number}</span><div><h2>{PATTERNS[kind].name} blueprint</h2><p>{kind==='dnb'?'Win/loss is relative to the team in each row. Draws are VOID.':kind==='btts'?'Did both teams score at least one goal by full time?':'The combined score of both teams at full time.'}</p></div></div><Status tone={summary?.current?'violet':'muted'} dot={summary?.current}>{summary?.current?'CURRENT SEASON':summary?.complete_days===30?'ARCHIVED SEASON':'PARTIAL ARCHIVE'}</Status></div>
      <div className="blueprint-meta"><Legend kind={kind}/><span>{summary?.complete_days||0}/30 matchdays verified <i/> Scores are H:A</span></div><ErrorBanner error={error}/>
      {loading&&!fp?<Loading/>:!teams.length?<Empty title={search?'No team matches your search':'This season is being collected'} description={search?'Clear the filter to view the full league.':'The collector will populate this blueprint as confirmed HT/FT records arrive.'}>{search&&<button className="button secondary" onClick={()=>setSearch('')}>Show all teams</button>}</Empty>:<div className={`fingerprint-scroll ${compact?'compact-mode':''}`}><div className="fingerprint-table"><div className="dna-table-header"><div className="dna-label">TEAM / MATCHDAY <ArrowRight size={12}/></div>{Array.from({length:30},(_,i)=><span key={i}>{String(i+1).padStart(2,'0')}</span>)}</div>{teams.map(t=><div className="dna-table-row" key={t.team}><div className="dna-label"><TeamBadge name={t.team} small/><div><strong>{t.team}</strong><small>{t.played}/30 recorded</small></div></div>{t.cards.map(card=><PatternCard card={card} kind={kind} mini={compact} onInspect={onInspect} key={card.day}/>)}</div>)}</div></div>}
      <div className="table-bottom"><span><ShieldIcon/>{num(confirmed)} confirmed team observations · {num(fp?.teams.length)} stored fingerprints for this blueprint</span><span className="scroll-hint">Scroll horizontally to see all 30 days <ArrowRight size={13}/></span></div>
    </div>
    <div className="explorer-bottom"><div className="notice"><Info size={19}/><div><strong>Every card is traceable.</strong><p>Select a score card to inspect its HT/FT result and source receipt. Playing and missing matchdays stay empty; the archive never guesses.</p></div></div><div className="compare-cta"><ScanLine size={25}/><div><h3>Recognize a sequence?</h3><p>Trace the current season through earlier team blueprints.</p></div><button className="button primary" onClick={()=>onNavigate('comparator')}>Open comparator<ArrowRight size={15}/></button></div></div>
  </>;
}
function ShieldIcon(){return <Fingerprint size={14}/>;}
