import React,{useEffect,useRef,useState} from 'react';
import {Target,UsersRound,Database,Check,ArrowRight,ChevronLeft,ChevronRight,RefreshCw,Info,Search,ScanLine,Focus,Loader2,HelpCircle,ChevronDown,Waypoints} from 'lucide-react';
import {Alignment} from './Comparator';
import {PageHead,TeamBadge,Status,Empty,Modal,num,pad,dateLabel} from './shared';
import {compareGold} from './model';

export function CorrectScoreCard({card,muted=false,mismatch=false,onInspect,withDay=false}){
 const filled=card?.ft!=null,title=filled?`MD ${card.day} · ${card.home} ${card.ft} ${card.away} · FT home:away · HT ${card.ht}`:`MD ${card?.day||'—'} · FT not captured`;
 return <button className={`pattern-card correct-score-card ${filled?'filled':'missing'} ${muted?'muted':''} ${mismatch?'mismatch':''}`} data-day={card?.day} data-score={card?.ft||''} disabled={!filled||!onInspect} title={title} aria-label={title} onClick={()=>onInspect?.(card.match_id)}>{withDay&&<small className="card-day">{pad(card.day)}</small>}<strong>{filled?'CS':'—'}</strong><span>{card?.ft||'·'}</span>{mismatch&&<b className="mismatch-dot">×</b>}</button>;
}

export default function Gold({workspace,data,mode,onInspect,onOpenTrail}){
 const roster=workspace.roster||[],up=data.upcoming||{};
 const [team,setTeam]=useState(roster[0]?.team||''),[scope,setScope]=useState('all'),[filter,setFilter]=useState(''),[tick,setTick]=useState(0),[analysis,setAnalysis]=useState(null),[analysisError,setAnalysisError]=useState(''),[busy,setBusy]=useState(true),[candidateIndex,setCandidateIndex]=useState(0),[manual,setManual]=useState({key:'',start:1}),[help,setHelp]=useState(false);
 const analysisKey=`${workspace.archive_id}:${workspace.results_revision}:${workspace.results.length}:${data.completed_prefix}:${up.season}:${up.day}:${roster.map(t=>t.team).join('|')}:${scope}:${tick}`;
 useEffect(()=>{let alive=true;setBusy(true);setAnalysisError('');const task=setTimeout(()=>{try{const result=compareGold(workspace,scope);if(alive)setAnalysis({key:analysisKey,result});}catch(e){if(alive)setAnalysisError(e.message);}finally{if(alive)setBusy(false);}},30);return()=>{alive=false;clearTimeout(task);};},[analysisKey]);
 useEffect(()=>{if(!roster.some(t=>t.team===team))setTeam(roster[0]?.team||'');},[roster.map(t=>t.team).join('|')]);
 useEffect(()=>setCandidateIndex(0),[team,scope]);
 const selected=roster.find(t=>t.team===team)||roster[0];
 const result=analysis?.key===analysisKey?analysis.result:null;
 const query=result?.teams.find(t=>t.team===selected?.team);
 const candidate=query?.candidates[candidateIndex]||query?.candidates[0];
 const candidateKey=`${analysisKey}:${team}:${query?.current_start}:${query?.length}:${candidate?.season}:${candidate?.team}:${candidate?.start}`;
 const start=manual.key===candidateKey?manual.start:candidate?.start||1;
 const matched=candidate?query.cards.reduce((count,c,i)=>count+Number(c.ft!=null&&c.ft===candidate.cards[start-1+i]?.ft),0):0;
 const exact=!!candidate&&matched===query.length;
 const detailRef=useRef(null);
 function focus(){return requestAnimationFrame(()=>{const scroll=detailRef.current?.querySelector('.alignment-scroll'),card=scroll?.querySelector('.current-row .pattern-card'),label=scroll?.querySelector('.current-row .dna-label');if(scroll&&card){const left=card.getBoundingClientRect().left-scroll.getBoundingClientRect().left+scroll.scrollLeft;scroll.scrollLeft=Math.max(0,left-(label?.getBoundingClientRect().width||160)-12);}});}
 useEffect(()=>{const frame=focus();return()=>cancelAnimationFrame(frame);},[candidateKey]);
 function choose(name){setTeam(name);setCandidateIndex(0);}
 function slide(n){setManual({key:candidateKey,start:Math.max(1,Math.min(31-query.length,Number(n)))});focus();}
 const visibleCards=selected?.cards.slice(0,selected.visible_until)||[];
 const prefix=selected?.prefix_length||0;
 const activeStart=query?.ready?query.current_start:1,activeEnd=query?.ready?query.current_end:prefix;
 const filtered=roster.filter(t=>t.team.toLowerCase().includes(filter.toLowerCase()));
 return <div className="gold-home"><PageHead eyebrow="CORRECT SCORE / DATA-FIRST WORKSPACE" title="Correct score gold hit pattern" description="Your incoming teams and their FT scores — visible before any historical comparison runs."><button className="button secondary" onClick={()=>setHelp(true)}><HelpCircle size={15}/>Matching rules</button><button className="button gold-button" onClick={()=>setTick(t=>t+1)}><RefreshCw size={15} className={busy?'spin':''}/>Recompare</button></PageHead>
  <div className="gold-data-bar"><div><span className="gold-data-icon"><UsersRound size={18}/></span><span><strong data-testid="incoming-count">{roster.length}</strong><small>incoming teams loaded</small></span></div><div><span className="gold-data-icon"><Database size={18}/></span><span><strong>{num(workspace.diagnostics.current_final_matches)}</strong><small>current-season FT records</small></span></div><div><span className="gold-data-icon"><ScanLine size={18}/></span><span><strong>{prefix}<em>rounds</em></strong><small>closed prefix from MD1</small></span></div><div className="gold-data-context"><b>SEASON {up.season||'—'} · INCOMING MD {up.day||'—'}</b><span>{mode==='live'?'Read from the collector':'Read from the saved Betika snapshot'}</span></div></div>
  <div className="gold-main-grid"><section className="panel incoming-panel"><header><div><span className="section-kicker">THE NEXT MATCHDAY</span><h2>Incoming teams <b>{roster.length}</b></h2></div><UsersRound size={18}/></header><label className="incoming-search"><Search size={14}/><input placeholder="Find an incoming team…" value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Search incoming teams"/>{filter&&<button onClick={()=>setFilter('')} aria-label="Clear incoming team filter">×</button>}</label><div className="incoming-list" role="group" aria-label="Incoming matchday teams">{filtered.map(t=>{const match=result?.teams.find(x=>x.team===t.team),preview=t.cards.slice(0,t.visible_until).filter(c=>c.ft!=null).slice(-2);return <button className={`incoming-team ${selected?.team===t.team?'selected':''}`} key={t.team} onClick={()=>choose(t.team)} aria-pressed={selected?.team===t.team} data-team={t.team} data-exact-count={match?.match_count??''}><TeamBadge name={t.team}/><div><strong>{t.team}</strong><span>{t.venue==='H'?'Home':t.venue==='A'?'Away':'Fixture'} {t.opponent?`· vs ${t.opponent}`:'details pending'}</span><div className="roster-score-preview">{preview.length?preview.map(c=><span key={c.day}><small>MD{c.day}</small><b>{c.ft}</b></span>):<span className="pending-ft">MD1 / MD2 · awaiting FT</span>}</div></div><span className={`incoming-hits ${match?.match_count?'has-hits':''}`}><b>{busy?'…':match?.ready?num(match.match_count):'—'}</b><small>{busy?'searching':match?.ready?'exact':'waiting'}</small></span></button>;})}{!filtered.length&&<div className="roster-empty">{roster.length?'No team matches this filter.':'No source-published fixture roster has been captured yet.'}</div>}</div><footer><Check size={12}/>{roster.length} recorded teams · source names, not sample data</footer></section>
  <div className="gold-detail" ref={detailRef}>
   <section className="panel ft-input-panel"><header><div className="ft-team-heading"><TeamBadge name={selected?.team||''}/><div><span className="section-kicker">FT SCORES TO COMPARE</span><h2>{selected?.team||'Waiting for the incoming roster'}</h2><p>Full-time scores are shown in website home:away order.</p></div></div><select aria-label="Choose incoming team" value={selected?.team||''} onChange={e=>choose(e.target.value)}>{roster.map(t=><option key={t.team} value={t.team}>{t.team}</option>)}</select></header>
    <div className="ft-input-summary"><span><b>{selected?.known_final_scores||0}</b> recorded FT scores</span><span>Source range <b>MD1–{selected?.visible_until||2}</b></span><span className="input-status"><i/>{busy?'Data loaded · checking history':query?.ready?'Data loaded · comparison ready':'Data shown · waiting for two closed rounds'}</span></div>
    <div className="ft-input-grid" aria-label="Current team full-time scores">{visibleCards.map(c=>{const used=c.comparison_eligible&&c.day>=activeStart&&c.day<=activeEnd;return <button key={c.day} className={`ft-input-card ${c.ft!=null?'recorded':'pending'} ${used?'used':''}`} disabled={!c.match_id} onClick={()=>c.match_id&&onInspect(c.match_id)} data-day={c.day} data-ft={c.ft||''} data-used={used} title={`MD${c.day} · ${c.ft!=null?`FT ${c.ft}${c.round_closed?'':' · round still closing'}`:c.observed_score?`Live ${c.observed_score} · not a final result`:'Awaiting a recorded final score'}`}><small>MD {pad(c.day)}</small><strong>{c.ft||'—'}</strong><span>{c.ft!=null?(used?'in query':!c.round_closed?'round open':'recorded'):c.state==='live'?'not FT yet':c.state==='missing'?'collecting':'awaiting FT'}</span></button>;})}</div>
    <div className="ft-input-explanation"><Info size={14}/><span>Gold cells are the actual input sequence. Other known FT scores stay visible. An empty score is pending or missing — never assumed to be 0:0.</span></div>
    <div className={`current-query ${query?.status||'loading'}`}><div><span className="section-kicker">CURRENT COMPARISON INPUT</span><strong>{query?.ready?`MD ${query.current_start}–${query.current_end} · ${query.length} consecutive FT results`:prefix<2?'Waiting for finalized MD1 and MD2':busy?`Checking the full MD1–${prefix} pattern…`:'The captured FT data is available above.'}</strong><p>{query?.status==='full'?'The full MD1-based sequence matched. No older day was excluded.':query?.status==='shortened'?`The full MD1–${query.full_length} sequence had no match. MD1–${query.trimmed_count} were excluded, one at a time, until this first matching length.`:query?.status==='no_match'?'The FT data is loaded, but no historical window matched the chosen sequence. Scores stay visible even when there are zero matches.':'Only closed rounds enter the comparison. Known later scores stay visible while missing earlier rounds are collected.'}</p></div><div className="current-query-count"><b>{busy?'…':query?.ready?num(query.match_count):'—'}</b><span>exact alignments</span></div></div>
   </section>
   <section className="panel gold-history-panel"><header><div><span className="section-kicker">EARLIER TEAM-SEASON BLUEPRINTS</span><h2>Historical comparison</h2></div><label><span>Compare with</span><select value={scope} onChange={e=>setScope(e.target.value)} aria-label="Gold historical team scope"><option value="all">All historical teams</option><option value="same">Same team only</option></select></label></header>
    {analysisError?<div className="history-message"><Info size={23}/><h3>Historical search needs attention</h3><p>{analysisError}</p><small>Your incoming teams and FT inputs are still available above.</small></div>:busy?<div className="history-message"><Loader2 className="spin" size={24}/><h3>Matching the recorded FT sequence…</h3><p>The roster and scores are already loaded. This search does not fetch or invent match data.</p></div>:candidate?<><div className="history-choice"><label><span>{query.length}-RESULT EXACT ALIGNMENTS</span><select aria-label="Choose correct score alignment" value={Math.min(candidateIndex,query.candidates.length-1)} onChange={e=>setCandidateIndex(Number(e.target.value))}>{query.candidates.map((c,i)=><option value={i} key={`${c.season}-${c.team}-${c.start}`}>{c.team} · S{c.season} · MD{c.start}–{c.end}</option>)}</select></label><div><span>{Math.min(candidateIndex+1,query.candidates.length)} / {query.candidates.length} shown{query.match_count>20?` of ${num(query.match_count)}`:''}</span><button className="icon-button" aria-label="Previous correct score alignment" disabled={candidateIndex<=0} onClick={()=>setCandidateIndex(i=>i-1)}><ChevronLeft size={16}/></button><button className="icon-button" aria-label="Next correct score alignment" disabled={candidateIndex>=query.candidates.length-1} onClick={()=>setCandidateIndex(i=>i+1)}><ChevronRight size={16}/></button></div></div><div className="gold-alignment-note"><span>Current MD{query.current_start}–{query.current_end} <ArrowRight size={12}/> Historical MD{start}–{start+query.length-1}</span><b>{matched}/{query.length} FT pairs {exact?'match':'at this offset'}</b></div>
     <Alignment kind="correct_score" CardComponent={CorrectScoreCard} currentLabel="CURRENT FT INPUT" currentTeam={selected.team} currentSeason={up.season} cards={query.cards} historicalTeam={candidate.team} historicalSeason={candidate.season} historicalCards={candidate.cards} start={start} onInspect={onInspect}/>
     <div className="alignment-controls"><div className="offset-control"><span>Historical start</span><div className="stepper"><button disabled={start<=1} aria-label="Move score alignment backward" onClick={()=>slide(start-1)}><ChevronLeft size={15}/></button><b>MD {pad(start)}</b><button disabled={start>=31-query.length} aria-label="Move score alignment forward" onClick={()=>slide(start+1)}><ChevronRight size={15}/></button></div><input type="range" min={1} max={31-query.length} value={start} onChange={e=>slide(e.target.value)} aria-label="Historical correct score start"/><button className="text-button" onClick={()=>{setManual({key:candidateKey,start:candidate.start});focus();}}>Reset alignment</button></div><button className="icon-button" aria-label="Focus matching scores" onClick={focus}><Focus size={16}/></button></div></>:<div className="history-message"><Target size={25}/><h3>{query?.ready?'No exact historical match':'Two finalized rounds are needed'}</h3><p>{query?.ready?'Every permitted sequence was checked, from the full prefix down to the first successful length or the two-result floor. No match is fabricated.':'Comparison starts from incoming MD3 after MD1 and MD2 close. This does not stop incoming team names or any already recorded FT scores from being shown.'}</p></div>}
    {!!query?.attempts.length&&<details className="gold-trace"><summary><span>See the exact search path</span><span>{query.attempts.length} length{query.attempts.length===1?'':'s'} checked<ChevronDown size={13}/></span></summary><div>{query.attempts.map(a=><span key={a.current_start} className={a.match_count?'hit':''}>MD{a.current_start}–{a.current_end}<b>{a.match_count} exact</b></span>)}</div></details>}
    <footer><span>{result?`${num(result.historical_blueprints)} historical blueprints · ${num(result.windows_scanned)} windows checked`:'Using captured Betika FT records'}</span><span>{result?`${result.compute_ms} ms local search`:'No prediction service required'}</span></footer>
   </section>
   <section className="trail-link-panel"><div><span className="trail-link-icon"><Waypoints size={20}/></span><div><span className="section-kicker">ONE EXACT MATCH → A LASTING ROW</span><h3>Single-hit Trail</h3><p>{(workspace.single_hit_rows||[]).filter(r=>r.current_season===up.season&&r.current_team===selected?.team&&r.scope===scope).length} saved historical pieces for {selected?.team||'this team'}. Keep each uniquely matching fragment aligned on a fixed MD1–30 canvas.</p></div></div><button className="button secondary" onClick={()=>onOpenTrail?.(selected?.team,scope)}>Open this team’s trail<ArrowRight size={14}/></button></section>
  </div></div>
  <div className="notice gold-honesty"><Info size={18}/><span><strong>Data display and matching are separate.</strong> All recorded incoming teams and FT scores remain available with zero matches, during collection, or in saved-snapshot mode. Exact historical agreement is not a next-score prediction.</span></div>
  {help&&<Modal title="The full FT sequence comes first" onClose={()=>setHelp(false)} wide><div className="methodology"><p className="lead">Incoming teams are read from the actual recorded fixtures. Current FT scores are read directly from match records — neither depends on the matching engine.</p><h3>Your matching rules</h3><ol className="gold-rules-list"><li>From upcoming MD3, once MD1 and MD2 are finalized, compare the complete MD1–2 FT sequence for each incoming team.</li><li>Append every newly finalized round: MD1–3, then MD1–4, and so on.</li><li>Try the full sequence at every valid starting day in earlier team-season blueprints.</li><li>From upcoming MD5 only, if there are no full-sequence matches, remove the oldest day one at a time.</li><li>Stop at the first matching length. Never use fewer than two results or mix different lengths into a team’s count.</li></ol><h3>Why some scores are not yet used</h3><p>A match can have a recorded FT before its entire round is closed. Earlier gaps also prevent the MD1-based prefix from growing. Those known scores remain visible, but they are not joined across gaps or mistaken for finalized rounds.</p><h3>Opening the saved app</h3><p>The standalone HTML contains a genuine captured archive. It works without an API server and is clearly labeled as a saved snapshot. For live data, run the included collector. The app replaces the snapshot with newer verified records when a live connection is available.</p><div className="notice"><Info size={18}/><span>Scores are literal FT home:away pairs. No team-relative reversal, forecast, betting confidence, account access or bet placement is provided.</span></div></div></Modal>}
 </div>;
}
