import React,{useState} from 'react';
import {Database, Radio, ShieldCheck, RefreshCw, Pause, Play, Download, ArrowUpRight, Info, Activity, CheckCheck, AlertTriangle, Clock3, HardDrive, CheckCircle2} from 'lucide-react';
import {PageHead,Status,Loading,Empty,ErrorBanner,useResource,api,num,ago,dateLabel,timeLabel} from './shared';

const endpointNames={'matches':'Upcoming fixtures','matches/ongoing':'Ongoing scores','matches/results':'History & finalized results','match':'Full market catalogue','competition':'League discovery'};
export default function Health({data,toast,onSync,syncing}){
  const [revision,setRevision]=useState(0),[working,setWorking]=useState(false);
  const {data:health,error,loading}=useResource('/api/health',`${data.fp_revision}-${revision}-${Math.floor(data.server_time/15)}`);
  async function pause(){setWorking(true);try{await api('/api/history/pause',{method:'POST',body:JSON.stringify({paused:!data.paused})});toast(data.paused?'History collection resumed.':'History paused. Live matchday collection is still running.');setRevision(v=>v+1);}catch(e){toast(e.message,'error');}finally{setWorking(false);}}
  async function retry(){try{const r=await api('/api/history/retry',{method:'POST'});toast(r.message);setRevision(v=>v+1);}catch(e){toast(e.message,'error');}}
  const back=data.backfill,db=health?.database;
  const healthy=Object.values(health?.endpoints||{}).filter(e=>e.ok).length,totalEndpoints=Object.keys(health?.endpoints||{}).length;
  return <><PageHead eyebrow="COLLECTION & PROVENANCE" title="Trust begins with the source." description="See what is stored, what is still missing, and exactly how the collector is doing."><a className="button secondary" href="/api/export/database" download onClick={()=>toast('Preparing a consistent SQLite backup…')}><Download size={16}/>Database backup</a><button className="button primary" onClick={onSync} disabled={syncing}><RefreshCw size={16} className={syncing?'spin':''}/>Sync now</button></PageHead><ErrorBanner error={error}/>
    <div className="health-cards"><article className="panel"><div className="health-card-heading"><span className="health-icon violet"><Database size={22}/></span><Status tone={db?.integrity==='ok'?'green':'amber'}>{db?.integrity==='ok'?'HEALTHY':'CHECKING'}</Status></div><h2>Durable by design.</h2><p>SQLite with write-ahead logging</p><div className="health-details"><span>Integrity check <b>{db?.integrity||'pending'}</b></span><span>Local read <b>{db?.read_ms??'—'} ms</b></span><span>Database size <b>{db?`${(db.size_bytes/1024/1024).toFixed(2)} MB`:'—'}</b></span></div><code>data/league.sqlite</code></article><article className="panel"><div className="health-card-heading"><span className="health-icon mint"><Radio size={22}/></span><Status tone={data.source.stale?'amber':'green'}>{data.source.stale?'DELAYED':'CONNECTED'}</Status></div><h2>One verified source.</h2><p>Betika's public website feeds</p><div className="health-details"><span>Competition <b>26 · Sakata League</b></span><span>Endpoints responding <b>{healthy} / {totalEndpoints}</b></span><span>Latest fixtures <b>{timeLabel(data.upcoming.fetched_at)} EAT</b></span></div><code>virtuals.betika.com</code></article><article className="panel"><div className="health-card-heading"><span className="health-icon blue"><Clock3 size={22}/></span><Status tone="violet">READ-ONLY</Status></div><h2>Always catching up.</h2><p>Polite polling, automatic reconciliation</p><div className="health-details"><span>Live / fixtures <b>5s / 10s target</b></span><span>Final results / markets <b>18s / 60s target</b></span><span>Global request limit <b>1 per second</b></span></div><code>No account or placement routes</code></article></div>
    <div className="panel backfill-panel"><div className="panel-head"><div><span className="icon-title"><HardDrive size={19}/><h2>Historical collection</h2></span><p>From season 3134345, using published season IDs — never guessed IDs.</p></div><div className="toolbar-right"><button className="button secondary small-button" onClick={retry}><RefreshCw size={14}/>Retry gaps</button><button className="button secondary small-button" onClick={pause} disabled={working}>{data.paused?<Play size={14}/>:<Pause size={14}/>} {data.paused?'Resume history':'Pause history'}</button></div></div><div className="backfill-progress"><div><span><b>{num(back.completed)}</b> / {num(back.expected)} source-published matchdays finalized</span><Status tone={back.state==='caught_up'?'green':back.state==='paused'?'amber':'violet'}>{back.state==='caught_up'?'CAUGHT UP':back.state==='paused'?'PAUSED':'COLLECTING'}</Status></div><div className="progress-track"><span style={{width:`${Math.min(100,back.percent||0)}%`}}/></div><div className="progress-caption"><span>{back.active_season&&back.state==='collecting'?`Currently checking S${back.active_season} / MD ${back.active_day}`:back.state==='caught_up'?'The archive is caught up with published final results.':'Newly playing rounds may remain provisional until all eight matches close.'}</span><b>{back.percent||0}%</b></div></div><div className="coverage-scroll"><div className="coverage-table"><div className="coverage-row header"><span>SEASON</span>{Array.from({length:30},(_,i)=><small key={i}>{String(i+1).padStart(2,'0')}</small>)}<b>COVERAGE</b></div>{data.seasons.map(s=><div className="coverage-row" key={s.id}><span><b>{s.id}</b>{s.current&&<i className="live-dot"/>}</span>{s.days.map(d=><span className={`coverage-cell ${d.error?'error':d.status}`} key={d.day} title={`Season ${s.id} · MD ${d.day} · ${d.final_count}/8 final${d.error?' · '+d.error:''}`}>{d.status==='complete'?<CheckCheck size={11}/>:d.error?'!':''}</span>)}<b>{s.complete_days}/30</b></div>)}</div></div><div className="coverage-key"><span><i className="complete"/>All 8 HT/FT pairs verified</span><span><i className="partial"/>Partial / playing / scheduled</span><span><i className="pending"/>Not yet stored / future</span><span><i className="error"/>Needs retry</span></div></div>
    <div className="health-bottom"><section className="panel endpoint-panel"><div className="panel-head"><div><span className="icon-title"><Radio size={18}/><h2>Communication points</h2></span><p>Observed in Betika’s public website scripts</p></div><Status tone="muted" dot={false}>GET ONLY</Status></div>{Object.entries(health?.endpoints||{}).map(([route,e])=><div className="endpoint" key={route}><span className={`endpoint-check ${e.ok?'ok':'bad'}`}>{e.ok?<CheckCircle2 size={17}/>:<AlertTriangle size={17}/>}</span><div><strong>{endpointNames[route]||route}</strong><code>/v1/{route}</code>{!e.ok&&<p>{e.error}</p>}</div><div><Status tone={e.ok?'green':'amber'} dot={false}>{e.ok?e.status:'ERROR'}</Status><small>{e.ok?`${e.latency_ms} ms`:ago(e.at)}</small></div></div>)}<div className="endpoint-foot"><ShieldCheck size={16}/>No betting, account, wallet or betslip endpoint is connected.</div></section>
    <section className="panel limitations"><div className="panel-head"><span className="icon-title"><Info size={18}/><h2>What to know</h2></span></div><article><span>01</span><div><h3>Discovery has a visible boundary.</h3><p>The website exposes a rolling list of 10 seasons. Your starting season was found and saved. Existing IDs stay in this archive; any undiscoverable gaps are not fabricated.</p></div></article><article><span>02</span><div><h3>Fast local reads. Source-dependent updates.</h3><p>Live scores are polled, not guaranteed push events. Provider delays, network time and rate limits can affect freshness. Stale observations are labeled.</p></div></article><article><span>03</span><div><h3>The collector must stay running.</h3><p>This preview collects while its server is active. For uninterrupted capture, deploy on an always-on host with a persistent data volume. Download a database backup regularly.</p></div></article><article><span>04</span><div><h3>Missing is not zero.</h3><p>Both confirmed HT and FT are required. No synthetic team names, placeholder scores or external match sources enter the application.</p></div></article></section></div>
    <section className="panel full-log"><div className="panel-head"><div className="icon-title"><Activity size={18}/><h2>Recent collection activity</h2></div><span className="muted-text">Latest 30 events · Africa/Nairobi</span></div>{(health?.activity||data.activity).slice(0,30).map(a=><div className={`log-row ${a.level}`} key={a.id}><time>{timeLabel(a.at)}</time><Status tone={a.level==='warning'?'amber':'muted'} dot={false}>{a.category}</Status><span>{a.message}</span>{a.level==='warning'?<AlertTriangle size={14}/>:<CheckCheck size={14}/>}</div>)}</section>
  </>;
}
