import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Fingerprint,GitCompareArrows,LibraryBig,Database,Search,ArrowRight,ChevronDown,HelpCircle,Menu,X,Radio,Moon,Sun,ShieldCheck,Check,AlertCircle,RefreshCw,Clock3,LockKeyhole,Info,Target,FileClock,Wifi,ExternalLink,Waypoints,ListTree,History,Crosshair,Microscope,Activity} from 'lucide-react';
import '@fontsource/inter/400.css';import '@fontsource/inter/500.css';import '@fontsource/inter/600.css';import '@fontsource/inter/700.css';
import '@fontsource/dm-sans/400.css';import '@fontsource/dm-sans/500.css';import '@fontsource/dm-sans/600.css';import '@fontsource/dm-sans/700.css';
import Overview,{MarketDrawer} from './Overview';
import Explorer from './Explorer';
import Comparator from './Comparator';
import Archive,{ResultInspector} from './Archive';
import Health from './Health';
import Gold from './Gold';
import Trail from './Trail';
import Sequences from './Sequences';
import Replay from './Replay';
import PlaygroundLive from './PlaygroundLive';
import PlaygroundEngines from './PlaygroundEngines';
import Matchups from './Matchups';
import BetikaEdge from './BetikaEdge';
import {api,useLive,Status,Loading,ErrorBanner,Methodology,Modal,num,timeLabel,dateLabel} from './shared';
import './styles.css';import './gold.css';import './trail.css';import './sequences.css';import './replay.css';import './playground.css';import './betika.css';

const NAV=[{id:'playground',label:'FT score Prediction Playground',icon:Crosshair},{id:'playground-engines',label:'Score engines & explainability',icon:Microscope},
{id:'matchups',label:'Head-to-head matchup DNA',icon:GitCompareArrows},{id:'gold',label:'Correct score gold',icon:Target},{id:'trail',label:'Single-hit trail',icon:Waypoints},{id:'sequences',label:'FT sequence explorer',icon:ListTree},{id:'replay',label:'Historical replay lab',icon:History},{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'explorer',label:'DNA explorer',icon:Fingerprint},{id:'comparator',label:'Pattern comparator',icon:GitCompareArrows},{id:'archive',label:'Results archive',icon:LibraryBig},{id:'health',label:'Data health',icon:Database},{id:'betika-edge',label:'Betika virtual edge analyzer',icon:Activity}];
function Logo(){return <div className="brand"><div className="brand-mark"><svg viewBox="0 0 36 40" fill="none"><path d="M9 6c0 12 18 16 18 28M27 6c0 12-18 16-18 28M10 10h16M13 18h10M13 23h10M10 31h16" stroke="currentColor" strokeWidth="2.6" strokeLinecap="round"/></svg></div><div>league<span>DNA</span><small>THE DATA-FIRST WORKSPACE</small></div></div>;}
function TopClock(){const [clock,setClock]=useState(Date.now()/1000);useEffect(()=>{const t=setInterval(()=>setClock(Date.now()/1000),1000);return()=>clearInterval(t);},[]);return <div className="top-clock"><Clock3 size={14}/><span>{timeLabel(clock)}<small> EAT</small></span></div>;}
function App(){
 const {data,workspace,error,connected,mode,refresh}=useLive();
 const currentPage=()=>NAV.some(n=>n.id===location.hash.slice(1))?location.hash.slice(1):'playground';
 const [page,setPage]=useState(currentPage),[navOpen,setNavOpen]=useState(false),[help,setHelp]=useState(false),[setup,setSetup]=useState(false),[market,setMarket]=useState(null),[inspect,setInspect]=useState(null),[initialTeam,setInitialTeam]=useState(''),[trailScope,setTrailScope]=useState('all'),[search,setSearch]=useState(''),[theme,setTheme]=useState(()=>{try{return localStorage.getItem('league-dna-theme')||'light';}catch{return 'light';}}),[message,setMessage]=useState(null),[syncing,setSyncing]=useState(false);
 useEffect(()=>{const change=()=>setPage(currentPage());addEventListener('hashchange',change);return()=>removeEventListener('hashchange',change);},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('league-dna-theme',theme);}catch{}},[theme]);
 useEffect(()=>{if(message){const t=setTimeout(()=>setMessage(null),6000);return()=>clearTimeout(t);}},[message]);
 useEffect(()=>{const key=e=>{if(e.target.matches('input,textarea,select'))return;if(e.key==='/'){e.preventDefault();document.querySelector('#global-search')?.focus();}if(e.key==='?')setHelp(true);if(e.key==='Escape')setNavOpen(false);};addEventListener('keydown',key);return()=>removeEventListener('keydown',key);},[]);
 function toast(text,type='success'){setMessage({text,type,id:Date.now()});}
 function navigate(to,team){setPage(to);if(['http:','https:','file:'].includes(location.protocol)){try{location.hash=to;}catch{}}setNavOpen(false);if(team){setInitialTeam(team);setSearch('');}else setInitialTeam('');window.scrollTo({top:0,behavior:'instant'});}
 async function sync(){if(mode!=='live'){setSetup(true);return;}setSyncing(true);try{const r=await api('/api/sync',{method:'POST'});toast(r.message);refresh();}catch(e){toast(e.message,'error');}finally{setSyncing(false);}}
 const selected=NAV.find(n=>n.id===page),fresh=mode==='live'&&data&&!data.source.stale,back=data?.backfill||{};
 const workspaceFree=['playground','playground-engines'].includes(page);
 return <div className="app-shell data-first-shell">{navOpen&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setNavOpen(false)}/>}<aside className={`sidebar ${navOpen?'open':''}`}><button className="brand-button" aria-label="League DNA home" onClick={()=>navigate('playground')}><Logo/></button><div className="workspace-switch"><span className="workspace-league-icon"><Target size={20}/></span><div><strong>Betika League</strong><span>Verified archive · read only</span></div><Check className="workspace-check" size={14}/></div><span className="nav-caption">YOUR WORKSPACE</span><nav aria-label="Main navigation">{NAV.map(n=><button key={n.id} className={`nav-item ${page===n.id?'active':''} ${n.id==='gold'?'gold-nav':n.id==='trail'?'trail-nav':n.id==='sequences'?'sequences-nav':n.id==='replay'?'replay-nav':n.id==='playground'?'playground-nav':n.id==='playground-engines'?'playground-nav':n.id==='matchups'?'playground-nav':''}`} onClick={()=>navigate(n.id)}><n.icon size={18}/><span>{n.label}</span>{n.id==='gold'?<span className="nav-new gold-nav-badge">INPUTS</span>:n.id==='comparator'?<span className="nav-new">LAB</span>:n.id==='playground'?<span className="nav-new gold-nav-badge">PICKS</span>:n.id==='matchups'?<span className="nav-new gold-nav-badge">H2H</span>:null}</button>)}</nav><div className="sidebar-rule"/><button className="nav-item help-nav" onClick={()=>setHelp(true)}><HelpCircle size={18}/><span>How it works</span></button><div className="sidebar-bottom"><div className="collector-card"><div><span>{mode==='live'?<Radio size={14}/>:<FileClock size={14}/>} {mode==='live'?'Collector connected':'Saved snapshot'}</span><i className={fresh?'green-dot':'amber-dot'}/></div><p>{mode==='live'?back.state==='caught_up'?'Verified archive is up to date.':'Collecting the source’s published rounds.':'Teams and scores remain available without a server.'}</p><div className="collector-progress"><span style={{width:`${Math.min(100,back.percent||0)}%`}}/></div><div className="collector-count"><span>{num(data?.counts.finalized)} finalized records</span></div><button onClick={()=>mode==='live'?navigate('health'):setSetup(true)}>{mode==='live'?'View collection status':'Enable live collection'}<ArrowRight size={13}/></button></div><button className="theme-control" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={16}/>:<Sun size={16}/>}<span>{theme==='light'?'Switch to dark canvas':'Switch to light canvas'}</span></button><div className="sidebar-foot"><LockKeyhole size={13}/><span>Read-only · real records</span><b>v2.9</b></div></div></aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setNavOpen(true)}><Menu size={20}/></button><span>Workspace</span><ChevronDown size={11} className="breadcrumb-divider"/><strong>{selected?.label}</strong></div><div className="topbar-right"><form className="global-search" onSubmit={e=>{e.preventDefault();navigate('explorer');}}><Search size={15}/><input id="global-search" placeholder="Find a team…" aria-label="Search all teams" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>/</kbd></form><div className={`top-live ${fresh?'':'delayed'}`}><span/>{fresh?'LIVE SOURCE':mode==='live'?'SOURCE DELAYED':'SAVED DATA'}</div><span className="topbar-divider"/><TopClock/><button className="profile-badge" aria-label="About workspace" onClick={()=>setHelp(true)}>LD</button></div></header>
 <main className="main-content"><div className="mobile-status"><Status tone={fresh?'green':'amber'}>{fresh?'Live source connected':'Saved records available'}</Status><TopClock/></div>
 {workspace&&<div className={`workspace-connection ${mode==='live'?'live':'snapshot'}`}><span>{mode==='live'?<Wifi size={16}/>:<FileClock size={16}/>}</span><div><strong>{mode==='live'?(fresh?'Live collector · data connected':'Collector connected · source observations delayed'):'Saved Betika snapshot — not a live feed'}</strong><small>{mode==='live'?`${workspace.roster.length} incoming teams · FT records loaded independently of comparison results`:`Captured ${dateLabel(workspace.captured_at)}. All included team names and scores are real captured records.`}</small></div><button onClick={()=>mode==='live'?refresh():setSetup(true)}>{mode==='live'?'Refresh data':'Live setup'}<ArrowRight size={13}/></button></div>}
 {!workspace&&!workspaceFree?<div className="startup"><Logo/><Loading text="Opening the recorded league workspace…"/><p>{error||'Reading the collector or the included source snapshot.'}</p><button className="button secondary" onClick={refresh}><RefreshCw size={16}/>Retry live connection</button><button className="text-button" onClick={()=>setSetup(true)}>How to open the standalone app</button></div>:<PageBoundary key={page} onReset={refresh}><>{page==='gold'&&<Gold workspace={workspace} data={data} mode={mode} onInspect={setInspect} onOpenTrail={(name,scope)=>{setTrailScope(scope);navigate('trail',name);}}/>} {page==='trail'&&<Trail workspace={workspace} data={data} mode={mode} initialTeam={initialTeam} initialScope={trailScope} onInspect={setInspect} onRefresh={refresh} toast={toast}/>}  {page==='playground'&&<PlaygroundLive/>} {page==='playground-engines'&&<PlaygroundEngines/>} {page==='matchups'&&<Matchups/>} {page==='replay'&&<Replay workspace={workspace} data={data} mode={mode} onInspect={setInspect} onRefresh={refresh}/>} {page==='sequences'&&<Sequences workspace={workspace} onInspect={setInspect}/>} {page==='overview'&&<Overview data={data} onNavigate={navigate} onMarket={setMarket} onInspect={setInspect} onSync={sync} syncing={syncing} toast={toast}/>} {page==='explorer'&&<Explorer data={data} initialTeam={initialTeam} globalSearch={search} onInspect={setInspect} onNavigate={navigate} toast={toast}/>} {page==='comparator'&&<Comparator data={data} onInspect={setInspect} toast={toast} onHelp={()=>setHelp(true)}/>} {page==='archive'&&<Archive data={data} onInspect={setInspect} toast={toast}/>} {page==='health'&&<>{mode!=='live'&&<div className="notice warning"><Info size={17}/><span>These are the database and source checks captured with the snapshot, not a current live health check. Collection controls require the running server.</span></div>}<Health data={data} toast={toast} onSync={sync} syncing={syncing}/></>} {page==='betika-edge'&&<BetikaEdge toast={toast}/>}<footer className="main-footer"><span><ShieldCheck size={13}/>Betika records only <i/> No fabricated teams or scores</span><span>{mode==='live'?'Collector connected':'Offline-capable snapshot'}<i/>{num(data?.counts?.finalized)} final results</span></footer><div className="responsible-footer">Independent research workspace · Historical matching is not a forecast · No wagering actions</div></></PageBoundary>}
 </main></div>{message&&<div className={`toast ${message.type}`} role="status" key={message.id}>{message.type==='error'?<AlertCircle size={19}/>:<Check size={19}/>}<span>{message.text}</span><button aria-label="Dismiss notification" onClick={()=>setMessage(null)}><X size={15}/></button></div>}{help&&<Methodology onClose={()=>setHelp(false)}/>} {setup&&<Setup onClose={()=>setSetup(false)} error={error}/>} {market&&<MarketDrawer id={market} onClose={()=>setMarket(null)} revision={workspace?.revision||0}/>} {inspect&&<ResultInspector id={inspect} onClose={()=>setInspect(null)} toast={toast}/>}</div>;
}
function Setup({onClose,error}){return <Modal title="Open it now. Connect live when ready." onClose={onClose} wide><div className="methodology"><p className="lead">The self-contained <b>League-DNA.html</b> file opens directly in a browser. Its incoming teams, FT scores, history and comparisons work without installing Python or running an API server.</p><h3>For continuous live collection</h3><ol className="gold-rules-list"><li>Extract the full <b>League-DNA-v2.3.zip</b> package.</li><li>On Windows, double-click <b>Start-League-DNA.cmd</b>. On macOS/Linux, run <b>Start-League-DNA.sh</b>. Python 3.11+ is required.</li><li>The launcher installs the Python requirements and opens <b>http://localhost:8000</b>. Keep its terminal open to collect new rounds.</li><li>Your records stay in <b>data/league.sqlite</b>. Never replace that file when upgrading an existing installation.</li></ol><h3>What the saved file means</h3><p>A snapshot displays the roster and scores as of its capture time. It does not claim those fixtures are still upcoming today. The live app replaces them with newer source observations when its collector connects.</p>{error&&<div className="notice"><Info size={17}/><span>Connection detail: {error}. This does not prevent reading saved teams and FT records.</span></div>}</div></Modal>;}
class PageBoundary extends React.Component{constructor(p){super(p);this.state={error:null};}static getDerivedStateFromError(error){return {error};}render(){return this.state.error?<div className="empty-state"><AlertCircle size={28}/><h3>This view needs to reload.</h3><p>The saved archive has not been changed. Other pages remain available.</p><button className="button secondary" onClick={()=>{this.setState({error:null});this.props.onReset?.();}}>Reload this view</button><p>{this.state.error.message}</p></div>:this.props.children;}}
createRoot(document.getElementById('root')).render(<App/>);
