import React,{useState} from 'react';
import {ArrowRight, ArrowUpRight, Fingerprint, Layers3, Database, ScanLine, Activity, Radio, Clock3, CheckCheck, Search, ShieldCheck, RefreshCw, Info, CircleDot, ChevronRight} from 'lucide-react';
import {PATTERNS,PageHead,TeamBadge,Status,PatternCard,Countdown,ExportButton,Legend,Modal,Empty,Loading,ErrorBanner,useResource,num,ago,timeLabel,scoreText} from './shared';

function HelixArt(){return <svg className="helix-art" viewBox="0 0 620 220" fill="none" aria-hidden="true"><defs><linearGradient id="helixA" x1="90" y1="0" x2="490" y2="200"><stop stopColor="#9477ee"/><stop offset="1" stopColor="#5736b9"/></linearGradient><linearGradient id="helixB" x1="80" y1="100" x2="600" y2="100"><stop stopColor="#9aaef3"/><stop offset="1" stopColor="#bce485"/></linearGradient><radialGradient id="glow"><stop stopColor="#fff" stopOpacity=".8"/><stop offset="1" stopColor="#fff" stopOpacity="0"/></radialGradient></defs><circle cx="355" cy="90" r="200" fill="url(#glow)"/><path d="M60 180C140 180 160 40 250 40S380 180 470 180S540 70 620 70" stroke="#ded5f6" strokeWidth="60" opacity=".25"/>{Array.from({length:28},(_,i)=>{const x=90+i*18;const y1=110+58*Math.sin((x-65)/64),y2=110-58*Math.sin((x-65)/64);return <g key={i}><line x1={x} y1={y1} x2={x} y2={y2} stroke={i%4===0?'#9fc777':'#b5a1e9'} strokeWidth="5" strokeLinecap="round" opacity=".65"/><circle cx={x} cy={y1} r="4" fill="#fff"/><circle cx={x} cy={y2} r="4" fill="#fff"/></g>;})}<path d="M70 114C129 185 154 181 210 111S302 35 360 108S453 184 510 112S572 48 620 55" stroke="url(#helixA)" strokeWidth="11" strokeLinecap="round"/><path d="M70 106C129 35 154 39 210 109S302 185 360 112S453 36 510 108S572 172 620 165" stroke="url(#helixB)" strokeWidth="11" strokeLinecap="round"/><circle cx="530" cy="40" r="24" fill="white" fillOpacity=".7"/><path d="m521 40 6 6 12-13" stroke="#7861bb" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><rect x="325" y="163" width="153" height="37" rx="10" fill="white" fillOpacity=".85"/><circle cx="344" cy="181" r="4" fill="#84b15d"/><text x="358" y="186" fill="#62576e" fontSize="11" fontFamily="Inter,sans-serif" letterSpacing="1">FOUR BLUEPRINTS</text></svg>;}

const marketName={main:'1X2',parity:'ODD/EVEN',btts:'BOTH TEAMS TO SCORE',dnb:'DRAW NO BET',total:'TOTAL'};
export function fixtureMarket(f,kind){
  const market=(f.markets||[]).find(m=>m.name.toUpperCase()===marketName[kind]);
  if(!market)return [];
  const options=kind==='total'?market.odds.filter(o=>o.specifier==='total=2.5'||/^((over|under)\s+2\.5)$/i.test(o.label)):market.odds;
  return options.map(o=>({...o,label:o.label.toUpperCase()}));
}
function FixtureCard({fixture:f,index,kind,onMarket,onDNA,live=false,liveStale=false}){
  const options=fixtureMarket(f,kind);const final=f.status==='final';
  return <article className={`fixture-card ${live?'live-card':''}`}><div className="fixture-top"><span>MATCH {String(index+1).padStart(2,'0')}</span>{live?<Status tone={final?'muted':liveStale?'amber':'green'} dot={!final}>{final?'FT':liveStale?'Last observed':'LIVE'}</Status>:<span className="fixture-id">#{f.event_id?.slice(-5)}</span>}</div><div className="fixture-teams"><div><TeamBadge name={f.home} small/><button className="team-link" onClick={()=>onDNA(f.home)}>{f.home}</button>{live?<b>{final?f.ft_home??'—':f.live_ft_home??'—'}</b>:<small>H</small>}</div><div><TeamBadge name={f.away} small/><button className="team-link" onClick={()=>onDNA(f.away)}>{f.away}</button>{live?<b>{final?f.ft_away??'—':f.live_ft_away??'—'}</b>:<small>A</small>}</div></div>{live?<><div className="live-score-strip"><span>HALF TIME{!final&&' · OBSERVED'}</span><strong>{scoreText(final?f.ht_home:f.live_ht_home,final?f.ht_away:f.live_ht_away)}</strong></div><div className="fixture-bottom"><span className="muted-text">{final?'Final scores verified':'Scores are provisional'}</span><Activity size={14}/></div></>:<><div className={`odds-grid odds-${options.length||3}`}>{options.length?options.map((o,i)=><div className="odd-readout" key={i}><span>{o.label}</span><strong>{o.value}</strong></div>):<div className="odds-pending">Market not yet collected</div>}</div><div className="fixture-bottom"><button onClick={()=>onMarket(f.event_id)}>{f.market_count?`${f.market_count} markets`:'View markets'}{!f.markets_full&&<small> syncing</small>}<ArrowUpRight size={13}/></button><button className="dna-link" onClick={()=>onDNA(f.home)} aria-label={`Explore ${f.home} DNA`}><Fingerprint size={15}/>DNA</button></div></>}</article>;
}

export default function Overview({data,onNavigate,onMarket,onInspect,onSync,syncing,toast}){
  const [view,setView]=useState('upcoming'),[market,setMarket]=useState('main'),[blueprint,setBlueprint]=useState('parity');
  const up=data.upcoming, live=data.ongoing,c=data.counts;
  const {data:fp}=useResource(data.current_season?`/api/blueprints?season=${data.current_season}&kind=${blueprint}`:null,data.fp_revision);
  const stats=[{label:'Seasons in the archive',value:num(c.seasons),icon:Layers3,foot:`${c.complete_seasons} fully collected`,tone:'violet'},
    {label:'Verified match results',value:num(c.finalized),icon:CheckCheck,foot:'Both half-time & full-time',tone:'mint'},
    {label:'Team fingerprints',value:num(c.fingerprints),icon:Fingerprint,foot:'4 independent blueprints',tone:'blue'},
    {label:'Matchdays preserved',value:num(c.complete_days),icon:Database,foot:`${data.backfill.percent||0}% of source-published rounds`,tone:'amber'}];
  return <><PageHead title="The league, decoded." description="Live matchdays. Team DNA. A history you can trace."><ExportButton toast={toast}/><button className="button primary" onClick={onSync} disabled={syncing}><RefreshCw size={16} className={syncing?'spin':''}/>Sync now</button></PageHead>
    <section className="hero"><div className="hero-copy"><span className="hero-tag"><ScanLine size={13}/>YOUR PATTERN LAB</span><h2>Every team has a story.<br/>Find it in the data.</h2><p>Four blueprints. Every matchday. One verified source.</p><button onClick={()=>onNavigate('explorer')}>Explore team DNA<ArrowRight size={15}/></button></div><HelixArt/><div className="hero-note"><span className="mini-dot"/>SOURCE-VERIFIED RECORDS</div></section>
    <div className="stats-grid">{stats.map(s=><article className="stat-card" key={s.label}><div className="stat-top"><span>{s.label}</span><span className={`stat-icon ${s.tone}`}><s.icon size={17}/></span></div><strong>{s.value}</strong><div className="stat-foot"><span className="tiny-dot"/>{s.foot}</div></article>)}</div>
    <section className="matchday-section"><div className="section-head"><div className="section-title"><h2>Matchday centre</h2><span className="subtle-label">BETIKA LEAGUE</span></div><span className="source-small"><ShieldCheck size={14}/>Direct from Betika</span></div><div className="matchday-toolbar"><div className="view-switch"><button className={view==='upcoming'?'active':''} onClick={()=>setView('upcoming')}>Upcoming <span>{up.day||'—'}</span></button><button className={view==='ongoing'?'active':''} onClick={()=>setView('ongoing')}><span className="live-dot"/>Ongoing <span>{live.day||'—'}</span></button></div><div className="toolbar-right">{view==='upcoming'&&<label className="market-select"><span>Market view</span><select value={market} onChange={e=>setMarket(e.target.value)} aria-label="Market view"><option value="main">1X2 · Full time</option><option value="parity">Odd / Even</option><option value="btts">Both teams to score</option><option value="dnb">Draw no bet</option><option value="total">Over / Under 2.5</option></select></label>}<Countdown start={up.start_time} serverTime={data.server_time} compact stale={data.source.stale}/></div></div>
      <div className="round-meta"><span>Season <b>{view==='upcoming'?up.season:live.season}</b><i/>Matchday <b>{view==='upcoming'?up.day:live.day}</b><i/>{view==='upcoming'?(up.fixtures?.length||0):(live.matches?.length||0)} matches</span><span>{view==='upcoming'?'Odds are read-only':`Last live observation ${timeLabel(live.fetched_at)} EAT`}<Info size={12}/></span></div>
      {(view==='upcoming'?up.fixtures:live.matches)?.length?<div className="fixtures-grid">{(view==='upcoming'?up.fixtures:live.matches).map((f,i)=><FixtureCard key={f.id} fixture={f} index={i} kind={market} onMarket={onMarket} onDNA={team=>onNavigate('explorer',team)} live={view==='ongoing'} liveStale={data.source.live_age_seconds>20}/>)}</div>:<div className="panel"><Empty title="Waiting for the next source snapshot" description="The public collector is checking Betika. Unknown matches are never filled with sample data." icon={Radio}/></div>}
    </section>
    <div className="overview-bottom"><section className="panel dna-snapshot"><div className="panel-head"><div><span className="icon-title"><Fingerprint size={19}/><h2>DNA at a glance</h2></span><p>Season {data.current_season} · settled full-time patterns</p></div><select value={blueprint} onChange={e=>setBlueprint(e.target.value)} aria-label="Snapshot blueprint">{Object.entries(PATTERNS).map(([k,p])=><option value={k} key={k}>{p.name}</option>)}</select></div><Legend kind={blueprint}/><div className="snapshot-list">{fp?.teams?.slice(0,5).map(t=><button className="snapshot-row" onClick={()=>onNavigate('explorer',t.team)} key={t.team}><span className="snapshot-name"><TeamBadge name={t.team} small/><b>{t.team}</b></span><span className="barcode">{t.cards.map((card,i)=><i title={`MD ${i+1}: ${card.ft||'not finalized'}`} key={i} className={card.code?`code-${blueprint}-${card.code}`:'missing'}/>)}</span><span className="snapshot-played">{t.played}<small>/30</small></span><ChevronRight size={15}/></button>)}{!fp?.teams?.length&&<Empty title="The first blueprints are forming" description="Confirmed results are being indexed from the public source."/>}</div><button className="panel-footer-link" onClick={()=>onNavigate('explorer')}>Explore all {data.teams.length} teams<ArrowRight size={15}/></button></section>
    <section className="panel activity-panel"><div className="panel-head"><div><span className="icon-title"><Activity size={18}/><h2>The collection log</h2></span><p>A clear trail from source to storage</p></div><span className="live-indicator"><i/>AUTO</span></div><div className="activity-list">{data.activity.slice(0,4).map(a=><div className="activity-item" key={a.id}><span className={`activity-icon ${a.level==='warning'?'warn':''}`}>{a.level==='warning'?<Info size={14}/>:<CheckCheck size={14}/>}</span><div><b>{a.category==='results'?'Matchday safely archived':a.category==='fixtures'?'Upcoming matchday refreshed':a.category==='discovery'?'Season discovered':'Collector update'}</b><p>{a.message}</p></div><time>{ago(a.at)}</time></div>)}</div><button className="panel-footer-link" onClick={()=>onNavigate('health')}>View data health<ArrowRight size={15}/></button></section></div>
  </>;
}

export function MarketDrawer({id,onClose,revision}){
  const {data,error,loading}=useResource(`/api/markets/${id}`,revision);const [search,setSearch]=useState('');
  const f=data?.fixture, markets=data?.markets?.filter(m=>`${m.name} ${m.odds.map(o=>o.label).join(' ')}`.toLowerCase().includes(search.toLowerCase()))||[];
  const expired=f?.start_time && f.start_time<=Date.now()/1000;
  return <Modal title="Market catalogue" onClose={onClose} drawer><div className="drawer-body"><ErrorBanner error={error}/>{loading&&!data?<Loading/>:data&&<><div className="market-match"><div><TeamBadge name={f?.home}/><strong>{f?.home}</strong></div><span>vs</span><div><TeamBadge name={f?.away}/><strong>{f?.away}</strong></div></div><div className="market-match-meta">Season {f?.season} · Matchday {f?.day} · Event {id}</div><div className={`notice ${expired?'warning':''}`}><Info size={17}/><span>{expired?'This fixture has reached its source start time. These are archived odds, not currently available prices.':'For reference only. Odds are source observations, not selections or recommendations.'}</span></div><div className="market-summary"><span><b>{data.markets.length}</b> {data.full?'published markets':'markets collected · full catalogue pending'}</span><span>{timeLabel(data.fetched_at)} EAT</span></div><label className="search-field"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a market or outcome…" aria-label="Search markets"/></label><div className="market-groups">{markets.map((m,i)=><section className="market-group" key={`${m.id}-${i}`}><h3>{m.name}<span>{m.odds.length}</span></h3><div className={`market-outcomes ${m.odds.length===2?'two':''}`}>{m.odds.map((o,j)=><div className="market-outcome" key={j} title={o.specifier||undefined}><span>{o.label}</span><strong>{o.value}</strong></div>)}</div></section>)}</div>{!markets.length&&<Empty title="No matching market" description="Try a team name, total, handicap or an outcome label."/>}<div className="drawer-end"><ShieldCheck size={16}/><span>Public Betika feed · source values preserved as published<br/>Last captured {timeLabel(data.fetched_at)} EAT · read-only</span></div></>}</div></Modal>;
}
