import React,{useEffect,useMemo,useRef,useState} from 'react';
import {History,Table2,Eye,EyeOff,ArrowRight,ChevronLeft,ChevronRight,ShieldCheck,Info,Focus,Download,HelpCircle,Play,RefreshCw,Radio,FileClock,TrendingUp,Check,X,Target} from 'lucide-react';
import {PageHead,TeamBadge,Status,Modal,num,pad,ago} from './shared';
import {downloadText} from './bridge';
import {replaySeasons,maxCutoff,replayTeams,replayReport,forecastFor,ledgerFor} from './replayModel';

export default function Replay({workspace,data,mode,onInspect,onRefresh}){
 const [tab,setTab]=useState('replay'),[season,setSeason]=useState(null),[team,setTeam]=useState(''),[cutoff,setCutoff]=useState(4),[length,setLength]=useState(4),[revealed,setRevealed]=useState(false),[help,setHelp]=useState(false);
 const key=`${workspace.archive_id}:${workspace.results_revision}:${workspace.results.length}:${data.current_season}`;
 const seasons=useMemo(()=>replaySeasons(workspace),[key]);
 const chosenEntry=seasons.find(s=>s.id===season)||seasons[0];
 const chosenSeason=chosenEntry?.id;
 const seasonMax=chosenEntry?maxCutoff(chosenEntry):29;
 const ongoing=Boolean(chosenEntry&&chosenEntry.prefix<30);
 const teams=useMemo(()=>chosenSeason?replayTeams(workspace,chosenSeason,seasonMax):[],[key,chosenSeason,seasonMax]);
 const chosenTeam=teams.includes(team)?team:teams[0]||'';
 const contextLength=Math.max(1,Math.min(length,cutoff));
 // The ongoing season opens at its finalized prefix so the live state is visible;
 // a finished season keeps the original MD4 default. When a new matchday is finalized
 // while the reader is at the frontier, the cutoff follows it; an earlier study
 // cutoff is left untouched.
 const view=useRef({season:null,limit:null});
 useEffect(()=>{
  if(!chosenEntry)return;
  const limit=maxCutoff(chosenEntry),previous=view.current;
  view.current={season:chosenEntry.id,limit};
  if(previous.season!==chosenEntry.id){
   const live=chosenEntry.prefix<30,start=live?limit:Math.min(4,limit);
   setCutoff(start);setLength(Math.min(4,start));setRevealed(false);setTeam('');
   return;
  }
  if(limit>previous.limit)setCutoff(prev=>prev>=previous.limit?limit:Math.min(limit,prev));
 },[chosenSeason,seasonMax]);
 useEffect(()=>setRevealed(false),[chosenSeason,chosenTeam,cutoff,contextLength]);
 const calculation=useMemo(()=>{if(!chosenSeason||!chosenTeam)return {report:null,error:''};try{return {report:replayReport(workspace,chosenSeason,chosenTeam,cutoff,contextLength,revealed),error:''};}catch(e){return {report:null,error:e.message};}},[key,chosenSeason,chosenTeam,cutoff,contextLength,revealed]);
 const report=calculation.report,evidence=report?.evidence;
 function setDay(value){const day=Math.max(1,Math.min(29,Number(value)));setCutoff(day);setLength(day);setRevealed(false);}
 function exportReplay(){if(!report)return;downloadText(`historical-replay-${chosenSeason}-md${cutoff}.json`,JSON.stringify({...report,scope:'Recorded source data only. Not an incoming-fixture forecast.'},null,2),'application/json');}
 const actualCount=report?.actual_next?evidence.outcomes.find(o=>o.score===report.actual_next.ft)?.matches||0:0;
 return <div className="replay-lab"><PageHead eyebrow="READ-ONLY RESEARCH / CHRONOLOGICAL REPLAY" title="Historical Replay Lab" description="Replay any recorded season matchday by matchday — including the ongoing season as it is finalized. Reference history stays strictly earlier, then reveal what actually happened."><button className="button secondary" onClick={()=>setHelp(true)}><HelpCircle size={15}/>Research method</button><button className="button replay-primary" onClick={exportReplay} disabled={!report||tab!=='replay'}><Download size={15}/>Export replay</button></PageHead>
  <AutoStrip workspace={workspace} data={data} mode={mode} onRefresh={onRefresh}/>
  <div className="replay-tabs" role="tablist" aria-label="Replay Lab view"><button role="tab" aria-selected={tab==='replay'} className={tab==='replay'?'active':''} onClick={()=>setTab('replay')}><History size={16}/>Season replay</button><button role="tab" aria-selected={tab==='board'} className={tab==='board'?'active':''} onClick={()=>setTab('board')}><Table2 size={16}/>Live FT board · {workspace.roster.length} teams</button></div>
  {tab==='board'?<LiveBoard workspace={workspace} data={data} mode={mode} onInspect={onInspect} onRefresh={onRefresh}/>:<>
   <div className="notice replay-boundary"><ShieldCheck size={18}/><span><strong>No target-season or later data enters the reference pool.</strong> The ongoing season can be replayed up to its finalized matchday, but its own later rounds and every later season stay excluded from the evidence.</span></div>
   <section className="panel replay-controls"><label><span>Target season</span><select aria-label="Replay target season" value={chosenSeason||''} onChange={e=>{setSeason(Number(e.target.value));setTeam('');setRevealed(false);}}>{seasons.map(s=><option key={s.id} value={s.id}>{s.id} · {s.prefix>=30?'30/30 finalized':`ongoing · MD${s.prefix} finalized`}</option>)}</select></label><label><span>Historical team</span><select aria-label="Replay historical team" value={chosenTeam} onChange={e=>{setTeam(e.target.value);setRevealed(false);}}>{teams.map(t=><option value={t} key={t}>{t}</option>)}</select></label><label><span>Visible through</span><select aria-label="Replay cutoff matchday" value={cutoff} onChange={e=>setDay(e.target.value)}>{Array.from({length:seasonMax},(_,i)=><option value={i+1} key={i}>Matchday {i+1}</option>)}</select></label><label><span>Ending context length</span><select aria-label="Replay context length" value={contextLength} onChange={e=>{setLength(Number(e.target.value));setRevealed(false);}}>{Array.from({length:cutoff},(_,i)=>cutoff-i).map(n=><option value={n} key={n}>{n} score{n===1?'':'s'}{n===cutoff?' · full prefix':''}</option>)}</select></label>{report&&<div className="replay-season-state"><Status tone={ongoing?'amber':'muted'}>{ongoing?`ONGOING · PREFIX MD${report.season_prefix}`:'COMPLETED SEASON'}</Status><small>{ongoing?`MD${report.season_prefix+1} is the next unplayed round; it appears automatically once the source finalizes it.`:'All 30 matchdays recorded.'}</small></div>}</section>
   {calculation.error&&<div className="notice warning"><Info size={16}/>{calculation.error}</div>}
   {!report?<div className="replay-empty"><History size={28}/><h3>A replayable season is required</h3><p>The ongoing season becomes replayable after its first finalized matchday, and earlier seasons appear as the archive fills.</p></div>:<>
    <section className="panel replay-timeline"><header><div><span className="replay-kicker">{ongoing?'ONGOING SEASON REPLAY · UPDATES WITH THE COLLECTOR':'RECORDED SEASON REPLAY'}</span><h2><TeamBadge name={chosenTeam} small/>{chosenTeam}<small>S{chosenSeason}</small></h2><p>Visible: MD1–{cutoff}. Selected context: MD{report.context_start}–{cutoff}. {report.next_day_recorded?`The recorded following result is MD${cutoff+1}.`:`MD${cutoff+1} has not been finalized by the source yet.`}</p></div><Status tone={ongoing?'amber':'muted'}>{ongoing?'ONGOING DATA':'COMPLETED DATA'}</Status></header><div className="replay-day-ruler">{Array.from({length:30},(_,i)=>{const day=i+1,card=day<=cutoff?report.visible_cards[i]:day===cutoff+1&&revealed?report.actual_next:null;const played=day<=report.season_prefix;const awaiting=day===cutoff+1&&!report.next_day_recorded;return <button className={`replay-day ${day<=cutoff?'visible':'withheld'} ${day>=report.context_start&&day<=cutoff?'context':''} ${day===cutoff+1?'next-day':''} ${day===cutoff+1&&revealed?'revealed':''} ${awaiting?'awaiting':''}`} key={day} disabled={!card} onClick={()=>card&&onInspect(card.match_id)} data-day={day} data-visible-score={card?.ft||''} title={card?`MD${day} recorded FT ${card.ft}`:awaiting?`MD${day} is the next round and has no finalized FT yet`:played?`MD${day} recorded but held out of this replay view`:`MD${day} has not been played yet`}><small>MD {pad(day)}</small><strong>{card?.ft||'?'}</strong><span>{day<=cutoff?(day>=report.context_start?'context':'visible'):day===cutoff+1?(awaiting?'awaiting FT':revealed?'revealed':'next · hidden'):played?'held out':'not played'}</span></button>;})}</div><div className="replay-cutoff"><button className="icon-button" aria-label="Move replay cutoff backward" disabled={cutoff<=1} onClick={()=>setDay(cutoff-1)}><ChevronLeft size={16}/></button><span>Cutoff <b>MD{pad(cutoff)}</b></span><input type="range" min={1} max={seasonMax} value={cutoff} onChange={e=>setDay(e.target.value)} aria-label="Historical replay cutoff slider"/><button className="icon-button" aria-label="Move replay cutoff forward" disabled={cutoff>=seasonMax} onClick={()=>setDay(cutoff+1)}><ChevronRight size={16}/></button>{report.next_day_recorded?<button className="button secondary small-button" onClick={()=>setRevealed(!revealed)}>{revealed?<EyeOff size={14}/>:<Eye size={14}/>} {revealed?'Hide recorded result':`Reveal recorded MD${cutoff+1}`}</button>:<button className="button secondary small-button" disabled title={`MD${cutoff+1} has no finalized FT yet. This view refreshes automatically.`}><Play size={14}/>MD{cutoff+1} awaiting FT</button>}</div></section>
    <div className="replay-summary"><div><span>Selected historical context</span><strong className="replay-context-text">{evidence.pattern.join(' → ')}</strong><small>Literal FT home:away order</small></div><div><span>Earlier reference seasons</span><strong>{report.reference_seasons.length}</strong><small>{report.reference_team_seasons} team-season blueprints</small></div><div><span>Recorded following matches</span><strong>{num(evidence.following_matches)}</strong><small>Distinct source match IDs</small></div><div><span>Context occurrences</span><strong>{num(evidence.occurrences)}</strong><small>{evidence.without_recorded_followup} without a known next FT</small></div></div>
    <div className="replay-references"><ShieldCheck size={16}/><span>{report.reference_seasons.length?<>Reference data: <b>S{report.reference_seasons[0]}–S{report.reference_seasons.at(-1)}</b>, all strictly before target <b>S{chosenSeason}</b>{ongoing?' (the ongoing season is never its own evidence)':''}.</>:<>This is the earliest retained season. There are no earlier reference seasons to use.</>}</span></div>
    <div className="replay-evidence-grid"><section className="panel replay-outcomes"><header><span className="replay-kicker">EARLIER HISTORY ONLY</span><h2>Recorded continuations</h2><p>What followed this exact context in the permitted historical reference pool.</p></header>{evidence.outcomes.length?<div>{evidence.outcomes.map(row=><div className={`replay-outcome ${revealed&&report.actual_next?.ft===row.score?'actual-observed':''}`} key={row.score} data-score={row.score} data-matches={row.matches}><b>{row.score}</b><span><strong>{row.matches}</strong> distinct recorded match{row.matches===1?'':'es'}<small>{row.traces} team-sequence observations · {row.seasons} seasons</small></span>{revealed&&report.actual_next?.ft===row.score&&<span className="replay-result-tag">Also recorded in target</span>}</div>)}</div>:<div className="replay-empty compact"><FileEmpty/><h3>No earlier continuation was recorded</h3><p>This is missing evidence, not permission to fill an outcome or use later seasons.</p></div>}<footer><Info size={13}/>{evidence.following_matches<10?`Small reference sample: ${evidence.following_matches} distinct following matches. No precision or confidence claim is made.`:'Observed counts are not future probabilities; repeated/overlapping records are not independent trials.'}</footer></section>
     <section className={`panel replay-actual ${revealed?'revealed':''}`}><span className="replay-kicker">{report.next_day_recorded?'ALREADY-RECORDED TARGET OUTCOME':'NEXT ROUND AWAITING THE SOURCE'}</span><h2>MD{cutoff+1}</h2><div className="replay-actual-score" data-revealed={revealed}>{revealed?report.actual_next.ft:report.next_day_recorded?'?':'…'}</div><p>{report.next_day_recorded?(revealed?'This is the real archived result, revealed after inspecting earlier reference data.':'The FT score is already in the archive, but is hidden from this replay view until you choose to reveal it.'):`MD${cutoff+1} has no finalized FT yet. The collector records it as soon as the source closes the round, and this panel updates automatically.`}</p><button className="button replay-primary" disabled={!report.next_day_recorded} onClick={()=>setRevealed(!revealed)}>{revealed?<EyeOff size={15}/>:<Eye size={15}/>} {revealed?'Hide actual result':report.next_day_recorded?'Reveal actual recorded result':`Waiting for MD${cutoff+1}`}</button>{revealed&&<><div className="replay-reveal-note"><b>{actualCount}</b> of {evidence.following_matches} earlier recorded follow-ups had this score.{actualCount===0&&<span>The reference sample did not contain the actual target continuation.</span>}</div><button className="text-button" onClick={()=>onInspect(report.actual_next.match_id)}>Inspect the target source record<ArrowRight size={13}/></button></>}<small>Never an incoming fixture. Never counted as reference evidence.</small></section>
    </div>
    <section className="panel replay-length-study"><header><span className="replay-kicker">CONTEXT-LENGTH STUDY</span><h2>Every trailing pattern ending at the cutoff</h2><p>Full MD1–{cutoff} first, then shorter suffixes. Selecting a length changes the historical lookup; it does not optimize a score pick.</p></header><div className="replay-length-head"><span>PATTERN / CURRENT REPLAY DAYS</span><span>OCCURRENCES</span><span>NEXT MATCHES</span><span>SEASONS</span></div>{report.length_study.map(row=><button className={row.length===contextLength?'selected':''} key={row.length} onClick={()=>{setLength(row.length);setRevealed(false);}} aria-label={`Study replay context length ${row.length}`}><span><small>MD{cutoff-row.length+1}–{cutoff} · {row.length} FT scores</small><b>{row.pattern.join(' → ')}</b></span><strong>{num(row.occurrences)}</strong><span>{num(row.following_matches)}</span><span>{row.context_seasons}</span></button>)}</section>
    <section className="panel replay-examples"><header><span className="replay-kicker">AUDIT THE REFERENCE ROWS</span><h2>Examples from earlier seasons</h2><p>The target season S{chosenSeason} and every later season are excluded from this list.</p></header>{evidence.examples.slice(0,15).map((example,i)=><div key={`${example.season}-${example.team}-${example.start}-${i}`} data-reference-season={example.season}><span><strong>{example.team}</strong><small>S{example.season} · MD{example.start}–{example.end}</small></span><span className="replay-example-context">{example.context.map(card=><button key={card.day} onClick={()=>onInspect(card.match_id)}><small>MD{card.day}</small><b>{card.ft}</b></button>)}</span><ArrowRight size={13}/><button className="replay-example-next" onClick={()=>onInspect(example.next.match_id)}><small>PAST MD{example.next_day}</small><b>{example.next.ft}</b></button></div>)}{!evidence.examples.length&&<p className="replay-no-examples">No valid earlier-season example exists for this context.</p>}<footer>Showing up to 15 earlier-source examples. Inspect any score to trace it to the captured Betika record.</footer></section>
   </>}
  </>}
  {help&&<Modal title="A replay experiment, not an incoming-score forecast" onClose={()=>setHelp(false)} wide><div className="methodology"><p className="lead">The lab separates live data display from recorded research, and it now covers the ongoing season as well as finished seasons.</p><h3>Chronological separation</h3><p>The selected target season is excluded from the reference pool in its entirety — even when that season is still being played. All later seasons are excluded too. A context score visible before the cutoff is used only as the lookup input.</p><h3>Ongoing seasons</h3><p>An unfinished season is replayable up to its contiguous finalized prefix. Cutoffs stop at that prefix, so a round with no recorded FT is never presented as if it existed. When the collector finalizes the next round, the cutoff range, the board and the reveal option extend automatically — the page refreshes every few seconds.</p><h3>Reveal the recorded result</h3><p>The next target result, when it exists, is already present in the source archive. It is visually hidden until you reveal it. This is a learning interface, not cryptographic blinding: the complete archive remains available elsewhere in the app.</p><h3>Live FT board continuation picks</h3><p>Each team row shows recorded current-season FT scores. The row directly beneath shows what that team's own finalized FT prefix continued into in earlier seasons: the longest matching context with at least two distinct recorded source matches is used, and the most frequently recorded following FT score becomes the pick. Every earlier matchday of the ongoing season is graded with only the context available before it, so each pick is marked correct or wrong. Exact-score repetition is rare; the ledger reports it rather than promising an edge.</p><div className="notice"><Info size={17}/><span>Historical repetition and small reference samples do not establish precise prediction or a betting edge. Existing Gold, Single-hit Trail, archive and live collector functionality are preserved.</span></div></div></Modal>}
 </div>;
}
function FileEmpty(){return <History size={25}/>;}
function AutoStrip({workspace,data,mode,onRefresh}){
 const live=mode==='live';
 return <div className={`auto-strip ${live?'live':'snapshot'}`} role="status"><span className="auto-strip-state">{live?<Radio size={14}/>:<FileClock size={14}/>}<strong>{live?'Auto-updating':'Saved snapshot'}</strong></span><span>{live?<><b>every 8s</b> · workspace refreshed {ago(workspace.captured_at)} · source observed {data.source?.stale?'over 35s ago':'within 35s'}</>:'Start the collector to auto-update matchday FT scores'}</span><span className="auto-strip-prefix">S{data.current_season} · MD1–{data.completed_prefix||0} finalized · MD{data.upcoming?.day} incoming</span><button className="button secondary small-button" onClick={()=>onRefresh?.()} disabled={!live} title={live?'Request the newest recorded workspace now':'Only the running collector can refresh live data'}><RefreshCw size={13}/>Refresh now</button></div>;
}
function ForecastSummary({forecast,scope,setScope,mode}){
 if(!forecast)return <div className="notice warning"><Info size={17}/><span>Continuation picks are unavailable in this payload. Rebuild the snapshot or run the collector to record the ledger.</span></div>;
 return <div className="forecast-summary">
  <div className="forecast-head"><span className="replay-kicker">EARLIER-SEASON CONTINUATION LEDGER</span><h3>FT score picks from recorded pattern continuations</h3><p>Each pick uses the longest context of that team's finalized FT prefix that has at least two distinct recorded matches in seasons strictly earlier than S{forecast.season}. The row under each team grades every earlier matchday with the context that was available before it.</p></div>
  <div className="forecast-totals"><div><span>Picks made</span><strong>{num(forecast.picks)}</strong></div><div><span>Exact FT hits</span><strong>{num(forecast.hits)}<small>{forecast.picks?` ${Math.round(forecast.hits/forecast.picks*1000)/10}%`:' —'}</small></strong></div><div><span>Wrong FT</span><strong>{num(forecast.misses)}</strong></div><div><span>Same winner</span><strong>{num(forecast.direction_hits)}<small>{forecast.direction_rate!=null?` ${forecast.direction_rate}%`:' —'}</small></strong></div><div><span>No qualifying evidence</span><strong>{num(forecast.no_pick)}</strong></div></div>
  <div className="forecast-controls"><span>Scope</span><div className="scope-switch" role="group" aria-label="Continuation scope"><button className={scope==='all'?'active':''} onClick={()=>setScope('all')}>All 16 teams</button><button className={scope==='same'?'active':''} onClick={()=>setScope('same')}>Same team only</button></div><span className="forecast-legend"><i className="legend hit"/><Check size={11}/> exact FT<i className="legend miss"/><X size={11}/> wrong FT<i className="legend pending"/><Target size={11}/> upcoming pick</span><small>{mode==='live'?'Recomputed whenever the collector finalizes an FT score.':'Snapshot values; rebuild to refresh.'}</small></div>
 </div>;
}
function LedgerCell({row,team,scope,onOpen}){
 if(!row)return <span className="ledger-cell blank" data-verdict="none" aria-hidden="true">·</span>;
 if(row.status==='no_pick')return <span className={`ledger-cell none`} data-day={row.day} data-verdict="no_pick" title={`MD${row.day} · ${row.reason==='context_too_short'?'not enough finalized days yet to build a context':'no earlier-season continuation reached the two-match minimum'}`}>—</span>;
 const verdict={hit:'✓',miss:'✗',pending:'PICK'}[row.status]||'?';
 return <button className={`ledger-cell ${row.status}`} data-day={row.day} data-verdict={row.status} data-pick={row.pick.score} data-actual={row.actual||''} data-scope={scope} title={`MD${row.day} · pick ${row.pick.score} from ${row.pick.matches} earlier recorded match${row.pick.matches===1?'':'es'} (${row.pick.share}%)${row.actual?` · recorded ${row.actual}`:' · awaiting the source'}`} onClick={()=>onOpen({team,scope,row})}><b>{row.pick.score}</b><small>{verdict}</small></button>;
}
function PickDetail({detail,cards,forecast,onClose,onInspect}){
 const {team,scope,row}=detail,pick=row.pick;
 const context=cards.slice(row.context_start-1,(row.context_start-1)+(row.context_length||0));
 return <Modal title={`MD${row.day} · ${team} continuation pick`} onClose={onClose} wide><div className="methodology pick-detail">
  <p className="lead">{row.status==='pending'?`Awaiting the source result for MD${row.day}.`:`This pick was graded ${row.status==='hit'?'correct':'wrong'} against the recorded FT.`} Scope: <b>{scope==='all'?'all 16 teams':'this team only'}</b> · engine {forecast?.engine||'earlier-season-continuation'} · reference seasons strictly before S{forecast?.season}.</p>
  <div className="pick-verdict"><div className={`pick-score ${row.status}`}><span>PICKED FT</span><strong>{pick?.score||'no pick'}</strong><small>{pick?`${pick.matches} distinct earlier match${pick.matches===1?'':'es'} · ${pick.share}% of ${pick.following_matches}`:'no qualifying continuation'}</small></div><ArrowRight size={16}/><div className={`pick-score actual ${row.status}`}><span>RECORDED FT</span><strong>{row.actual||'—'}</strong><small>{row.actual?`${row.status==='hit'?'exact match':'different score'}${row.direction_hit?' · same winner':''}`:'not finalized yet'}</small></div></div>
  {context.length>0&&<><h3>Context used ({pick.context_start?`MD${pick.context_start}–MD${(pick.context_start||0)+(pick.context_length||0)-1}`:'—'})</h3><div className="pick-context">{context.map(card=><button key={card.day} onClick={()=>onInspect(card.match_id)} disabled={!card.match_id}><small>MD{card.day}</small><b>{card.ft}</b></button>)}</div></>}
  {pick?.outcomes?.length?<><h3>Recorded earlier continuations</h3><div className="pick-outcomes">{pick.outcomes.map(outcome=><div key={outcome.score} className={outcome.score===pick.score?'chosen':''}><b>{outcome.score}</b><span>{outcome.matches} distinct match{outcome.matches===1?'':'es'} · {outcome.traces} observations · {outcome.seasons} seasons</span></div>)}</div></>:<p>No earlier-season continuation reached the two-match minimum for any context ending at this matchday.</p>}
  {pick?.attempts&&<><h3>Why this context length</h3><p>The full visible prefix is always tried first; the oldest day is only dropped when no continuation was recorded.</p><div className="pick-attempts">{pick.attempts.map(attempt=><div key={attempt.length} className={attempt.length===pick.length?'chosen':''}><span>MD{attempt.context_start}–MD{attempt.context_start+attempt.length-1}</span><b>{attempt.following_matches}</b><small>{attempt.following_matches?'recorded':'none'}</small></div>)}</div></>}
  <div className="notice"><Info size={17}/><span>Recorded repetition, not a probability. No missing score is filled in, no later season is used, and no wagering action is offered.</span></div>
 </div></Modal>;
}
function LiveBoard({workspace,data,mode,onInspect,onRefresh}){
 const [search,setSearch]=useState(''),[scope,setScope]=useState('all'),[detail,setDetail]=useState(null);
 const scroll=useRef(null);
 const forecast=useMemo(()=>forecastFor(workspace,scope),[workspace,scope]);
 const byTeam=useMemo(()=>new Map((forecast?.teams||[]).map(row=>[row.team,row])),[forecast]);
 const roster=workspace.roster.filter(t=>t.team.toLowerCase().includes(search.toLowerCase()));
 function focus(day){requestAnimationFrame(()=>{const el=scroll.current,card=el?.querySelector(`.live-board-row [data-day="${day}"]`),label=el?.querySelector('.live-board-team');if(el&&card){const left=card.getBoundingClientRect().left-el.getBoundingClientRect().left+el.scrollLeft;el.scrollLeft=Math.max(0,left-(label?.getBoundingClientRect().width||170)-12);}});}
 return <><div className="notice replay-boundary"><Table2 size={18}/><span><strong>Recorded FT scores plus earlier-season continuation picks.</strong> The {workspace.roster.length} incoming teams keep their recorded current-season FT values; the row beneath each team lists every pick made for that team and whether the recorded FT matched it exactly.</span></div><section className="panel live-board"><header><div><span className="replay-kicker">{mode==='live'?'COLLECTOR DATA · AUTO-UPDATING':'SAVED SOURCE SNAPSHOT'}</span><h2>All {workspace.roster.length} incoming teams · S{data.current_season}</h2><p>Incoming matchday {data.upcoming?.day} · finalized prefix MD1–{data.completed_prefix||0} · scores are literal FT home:away.</p></div><div><input aria-label="Filter live FT board teams" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filter team…"/><button className="button secondary small-button" onClick={()=>focus(1)}>MD1</button><button className="button secondary small-button" onClick={()=>focus(Math.max(1,data.completed_prefix||1))}><Focus size={13}/>Latest FT</button><button className="button secondary small-button" onClick={()=>onRefresh?.()} disabled={mode!=='live'}><RefreshCw size={13}/>Refresh</button></div></header>
  <ForecastSummary forecast={forecast} scope={scope} setScope={setScope} mode={mode}/>
  <div className="live-board-scroll" ref={scroll}><div className="live-board-canvas"><div className="live-board-grid live-board-ruler"><div className="live-board-team">CURRENT TEAM / MATCHDAY</div>{Array.from({length:30},(_,i)=><span key={i}>{pad(i+1)}</span>)}</div>{roster.map(team=>{const analysis=byTeam.get(team.team);const ledger=new Map((analysis?.ledger||[]).map(row=>[row.day,row]));return <React.Fragment key={team.team}><div className="live-board-grid live-board-row" data-team={team.team}><div className="live-board-team"><span><TeamBadge name={team.team} small/><strong>{team.team}</strong></span><small>{team.venue==='H'?'Home':'Away'} · vs {team.opponent||'fixture pending'}</small></div>{team.cards.map(card=>{const live=card.ft==null&&card.observed_score?card.observed_score:null;return <button key={card.day} className={`live-board-score ${card.ft!=null?'final':'pending'} ${card.state==='live'?'playing':''} ${card.day===data.upcoming?.day?'incoming-day':''}`} disabled={!card.match_id} onClick={()=>onInspect(card.match_id)} data-day={card.day} data-score={card.ft||''} data-live={live||''} title={`MD${card.day} · ${card.ft!=null?'Recorded FT '+card.ft:card.state==='live'?'Playing; not finalized'+(live?` · current source score ${live}`:''):'No final score recorded'}`}><strong>{card.ft||live||'—'}</strong><small>{card.ft!=null?'FT':card.state==='live'?(live?'LIVE FT':'LIVE'):'—'}</small></button>;})}</div>
   <div className="live-board-grid live-board-ledger-row" data-team={team.team} data-scope={scope}><div className="live-board-team ledger-team"><span><TrendingUp size={12}/><strong>{team.team} picks</strong></span><small data-summary={analysis?`${analysis.summary.hits}/${analysis.summary.picks}`:'none'}>{analysis?`${analysis.summary.picks} picks · ${analysis.summary.hits} exact · ${analysis.summary.misses} wrong${analysis.summary.no_pick?` · ${analysis.summary.no_pick} no evidence`:''}`:'No ledger'}</small></div>{team.cards.map(card=><LedgerCell key={card.day} row={ledger.get(card.day)} team={team.team} scope={scope} onOpen={setDetail}/>)}</div></React.Fragment>;})}</div></div><footer><ShieldCheck size={13}/>{roster.length} teams displayed. Unknown scores are never filled with 0:0. Click a recorded score for its source evidence, or a pick for its historical continuation evidence.</footer></section>
  {detail&&<PickDetail detail={detail} cards={(workspace.roster.find(row=>row.team===detail.team)?.cards)||[]} forecast={forecast} onClose={()=>setDetail(null)} onInspect={id=>{setDetail(null);onInspect(id);}}/>}</>;
}
