import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,Plus,X,Search,Database,Info,Layers3,ListFilter,ChevronLeft,ChevronRight,FileSearch,Hash,Download,HelpCircle} from 'lucide-react';
import {PageHead,Status,Modal,num,dateLabel} from './shared';
import {scoreVocabulary,historicalFollowers,observedCatalogue,validateSequence} from './sequenceModel';
import {downloadText,isOnline} from './bridge';

const EXAMPLES=[['0:0','0:1'],['1:2','0:1'],['1:1','0:1','1:4']];
export default function Sequences({workspace,onInspect}){
 const [pattern,setPattern]=useState(EXAMPLES[0]),[draft,setDraft]=useState(EXAMPLES[0].join(', ')),[error,setError]=useState(''),[outcome,setOutcome]=useState(''),[length,setLength]=useState(2),[page,setPage]=useState(0),[tab,setTab]=useState('followups'),[help,setHelp]=useState(false);
 const sourceKey=`${workspace.archive_id}:${workspace.results_revision}:${workspace.results.length}`;
 const vocabulary=useMemo(()=>scoreVocabulary(workspace),[sourceKey]);
 const stats=useMemo(()=>historicalFollowers(workspace,pattern),[sourceKey,pattern.join('|')]);
 const library=useMemo(()=>tab==='library'?observedCatalogue(workspace,length):[],[sourceKey,tab,length]);
 const pages=Math.max(1,Math.ceil(library.length/25)),shown=library.slice(Math.min(page,pages-1)*25,(Math.min(page,pages-1)+1)*25);
 const examples=stats.examples.filter(e=>!outcome||e.next.ft===outcome).slice(0,30);
 const index=workspace.sequence_index;
 useEffect(()=>setPage(0),[length]);
 function apply(values){setPattern(values);setDraft(values.join(', '));setOutcome('');setError('');setTab('followups');}
 function submit(e){e.preventDefault();try{apply(validateSequence(draft));}catch(e){setError(e.message);}}
 function exportObserved(){const lines=['context,following_ft,distinct_recorded_matches,team_sequence_observations,seasons'];for(const row of stats.outcomes)lines.push(`"${pattern.join(' → ')}",${row.score},${row.matches},${row.traces},${row.seasons}`);downloadText('historical-ft-followups.csv',lines.join('\n'),'text/csv;charset=utf-8');}
 const theoretical=(BigInt(vocabulary.length||0)**BigInt(length)).toString();
 return <div className="sequence-workspace"><PageHead eyebrow="HISTORICAL FT SEQUENCE LIBRARY" title="What followed this sequence?" description="Explore every observed full-time pattern and the scores recorded immediately after it. Historical counts — not upcoming-fixture picks."><button className="button secondary" onClick={()=>setHelp(true)}><HelpCircle size={15}/>Read the method</button><button className="button sequence-button" onClick={exportObserved} disabled={!stats.outcomes.length}><Download size={15}/>Export observed counts</button></PageHead>
  <div className="sequence-source-strip"><Database size={19}/><div><strong>{num(vocabulary.length)} unique FT scores found in the source archive</strong><span>{index?.observed_patterns?`${num(index.observed_patterns)} observed patterns indexed across lengths 1–30 · ${dateLabel(index.updated_at)}`:'The persistent index is built by the updated collector. Local analysis already works from captured match records.'}</span></div><Status tone="muted">HISTORICAL ONLY</Status></div>
  <div className="sequence-tabs" role="tablist" aria-label="Sequence analysis view"><button role="tab" aria-selected={tab==='followups'} className={tab==='followups'?'active':''} onClick={()=>setTab('followups')}><FileSearch size={16}/>Pattern follow-ups</button><button role="tab" aria-selected={tab==='library'} className={tab==='library'?'active':''} onClick={()=>setTab('library')}><Layers3 size={16}/>Observed pattern library</button><button role="tab" aria-selected={tab==='scores'} className={tab==='scores'?'active':''} onClick={()=>setTab('scores')}><Hash size={16}/>Unique FT scores</button></div>
  {tab==='followups'&&<><section className="panel sequence-builder"><header><div><span className="section-kicker">ENTER A PAST SCORE CONTEXT</span><h2>Build a sequence to look up</h2></div><span>{pattern.length} result{pattern.length===1?'':'s'} · order preserved</span></header><div className="sequence-token-row">{pattern.map((score,i)=><React.Fragment key={i}>{i>0&&<ArrowRight size={15}/>}<div className="sequence-token"><span>POSITION {i+1}</span><select aria-label={`FT score at position ${i+1}`} value={score} onChange={e=>apply(pattern.map((s,j)=>j===i?e.target.value:s))}>{!vocabulary.some(v=>v.score===score)&&<option value={score}>{score} · unobserved</option>}{vocabulary.map(v=><option key={v.score} value={v.score}>{v.score}</option>)}</select><button aria-label={`Remove position ${i+1}`} disabled={pattern.length===1} onClick={()=>apply(pattern.filter((_,j)=>i!==j))}><X size={12}/></button></div></React.Fragment>)}<button className="sequence-add" disabled={pattern.length>=30} onClick={()=>apply([...pattern,vocabulary[0]?.score||'0:0'])}><Plus size={17}/><span>Add FT</span></button></div><form className="sequence-text-form" onSubmit={submit}><label><span>Or paste a sequence</span><input value={draft} onChange={e=>setDraft(e.target.value)} aria-label="FT sequence text" placeholder="0:0, 0:1"/></label><button className="button sequence-button"><Search size={14}/>Look up history</button></form>{error&&<div className="sequence-validation" role="alert">{error}</div>}<div className="sequence-examples"><span>Try your examples</span>{EXAMPLES.map((example,i)=><button key={i} onClick={()=>apply(example)}>{example.join(' → ')}</button>)}</div></section>
   <div className="sequence-metrics"><div><span>Pattern occurrences</span><strong>{num(stats.occurrences)}</strong><small>Across recorded team-season sequences</small></div><div><span>Known following matches</span><strong>{num(stats.following_matches)}</strong><small>Distinct source match IDs, deduplicated</small></div><div><span>Different following FT scores</span><strong>{num(stats.outcomes.length)}</strong><small>All observed outcomes are shown</small></div><div><span>Seasons containing this context</span><strong>{num(stats.context_seasons)}</strong><small>{num(stats.without_recorded_followup)} occurrence{stats.without_recorded_followup===1?'':'s'} without a recorded next FT</small></div></div>
   <div className={`notice sequence-evidence-note ${stats.following_matches<10?'warning':''}`}><Info size={18}/><span>{stats.following_matches===0?<><strong>No recorded following outcome is available.</strong> A context may be unseen, end at MD30, or have an unrecorded following round. Nothing is inferred to fill that gap.</>:stats.following_matches<10?<><strong>Very small historical sample: {stats.following_matches} distinct following match{stats.following_matches===1?'':'es'}.</strong> Even a single outcome accounting for every recorded case does not establish a reliable next-score forecast.</>:<><strong>These are observed frequencies, not predictive probabilities.</strong> Repeated team trajectories and overlapping windows are dependent. No outcome is recommended for an incoming fixture.</>}</span></div>
   <div className="sequence-analysis-grid"><section className="panel sequence-outcomes"><header><div><span className="section-kicker">IMMEDIATELY FOLLOWING FT · RECORDED HISTORY</span><h2>After {pattern.join(' → ')}</h2><p>{stats.following_matches?`The archive contains ${stats.following_matches} distinct following matches and ${stats.following_traces} team-sequence observations.`:'No past outcome is available for this exact context.'}</p></div><span className="sequence-unit">Not a prediction</span></header>{stats.outcomes.length?<div className="sequence-outcome-table"><div className="sequence-outcome-head"><span>FOLLOWING FT</span><span>DISTINCT MATCHES / RECORDED SHARE</span><span>SEASONS</span></div>{stats.outcomes.map(row=><button className={`sequence-outcome-row ${outcome===row.score?'selected':''}`} key={row.score} onClick={()=>setOutcome(outcome===row.score?'':row.score)} aria-label={`Show historical examples ending ${row.score}`}><b>{row.score}</b><div><span><strong>{num(row.matches)}</strong> of {num(stats.following_matches)} recorded{stats.following_matches>=5&&<em>{row.historical_share}%</em>}</span><i><span style={{width:`${row.historical_share}%`}}/></i><small>{row.traces} team-sequence observation{row.traces===1?'':'s'}</small></div><span>{row.seasons}</span></button>)}</div>:<div className="sequence-empty"><FileSearch size={27}/><h3>No historical follow-up to report</h3><p>Try a different observed context. Unseen combinations are not assigned fabricated outcomes.</p></div>}</section><section className="panel sequence-season-table"><header><span className="section-kicker">COVERAGE, NOT CONFIDENCE</span><h2>Where the evidence comes from</h2><p>Counts by recorded season make sparse or uneven coverage visible.</p></header><div className="sequence-season-head"><span>SEASON</span><span>CONTEXTS</span><span>NEXT MATCHES</span></div>{stats.seasons.map(row=><div className="sequence-season-row" key={row.season}><span>{row.season}</span><b>{row.occurrences}</b><span>{row.following_matches}<small>{row.distinct_outcomes} FT types</small></span></div>)}{!stats.seasons.length&&<p className="sequence-no-seasons">No recorded season contains this exact pattern.</p>}<footer>A pattern occurrence at the end of a season does not wrap around to the next season's MD1.</footer></section></div>
   <section className="panel sequence-records"><header><div><span className="section-kicker">TRACE THE ACTUAL MATCHES</span><h2>Historical examples {outcome&&<small>· following FT {outcome}</small>}</h2><p>Each row is a past team trajectory, not an upcoming match suggestion. Click its recorded following score to inspect the source result.</p></div>{outcome&&<button className="text-button" onClick={()=>setOutcome('')}>Clear outcome filter<X size={12}/></button>}</header>{examples.length?<div className="sequence-record-list">{examples.map((example,i)=><div className="sequence-record" key={`${example.season}-${example.team}-${example.start}-${i}`}><div><strong>{example.team}</strong><small>S{example.season} · MD{example.start}–{example.end}</small></div><span className="sequence-record-context">{example.context.map(c=><button key={c.day} onClick={()=>onInspect(c.match_id)} title={`Historical MD${c.day}, FT ${c.ft}`}><small>MD{c.day}</small><b>{c.ft}</b></button>)}</span><ArrowRight size={14}/><button className="sequence-next-record" onClick={()=>onInspect(example.next.match_id)} aria-label={`Inspect recorded following match ${example.next.match_id}`}><small>PAST MD{example.next_day}</small><strong>{example.next.ft}</strong><span>source result</span></button></div>)}</div>:<div className="sequence-empty small"><p>No known following-score examples are available.</p></div>}<footer>Showing up to 30 team-sequence examples. Two opponents can lead to the same next match; the distribution above deduplicates that source match ID.</footer></section>
  </>}
  {tab==='library'&&<section className="panel sequence-library"><header><div><span className="section-kicker">SPARSE, OBSERVED PATTERNS</span><h2>Browse the pattern catalogue</h2><p>Every listed combination actually occurs in recorded FT data.</p></div><label><span>Context length</span><select aria-label="Catalogue pattern length" value={length} onChange={e=>setLength(Number(e.target.value))}>{Array.from({length:30},(_,i)=><option value={i+1} key={i}>{i+1} FT score{i?'s':''}</option>)}</select></label></header><div className="sequence-combinatorics"><span><b>{num(library.length)}</b> observed patterns of length {length}</span><span>{vocabulary.length}<sup>{length}</sup> theoretical combinations: <b>{theoretical.length>18?`${theoretical.slice(0,3)}… (${theoretical.length} digits)`:Number(theoretical).toLocaleString('en-KE')}</b></span><p>The database stores observed evidence only. An unobserved combination has no recorded next outcome, not an invented probability.</p></div><div className="sequence-library-head"><span>RECORDED PATTERN</span><span>OCCURRENCES</span><span>NEXT MATCHES</span><span/></div>{shown.map(row=><button className="sequence-library-row" key={row.pattern.join('|')} onClick={()=>apply(row.pattern)}><span>{row.pattern.map((score,i)=><React.Fragment key={i}>{i>0&&<ArrowRight size={10}/>}<b>{score}</b></React.Fragment>)}</span><strong>{num(row.occurrences)}</strong><span>{num(row.following_matches)}</span><FileSearch size={15}/></button>)}<footer className="sequence-library-pagination"><span>Page {Math.min(page,pages-1)+1} / {num(pages)} · {num(library.length)} observed patterns</span><div><button className="icon-button" aria-label="Previous catalogue page" disabled={page<=0} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/></button><button className="icon-button" aria-label="Next catalogue page" disabled={page>=pages-1} onClick={()=>setPage(p=>p+1)}><ChevronRight size={16}/></button></div></footer></section>}
  {tab==='scores'&&<section className="panel sequence-vocabulary"><header><span className="section-kicker">THE ACTUAL FT ALPHABET</span><h2>{vocabulary.length} unique full-time scores</h2><p>Scanned from finalized source matches. Counts here count each physical match once, not twice for the two teams.</p></header><div>{vocabulary.map(v=><button key={v.score} onClick={()=>apply([v.score])} aria-label={`Analyze FT ${v.score}`}><strong>{v.score}</strong><span>{num(v.matches)} matches</span><small>Inspect observed follow-ups<ArrowRight size={11}/></small></button>)}</div></section>}
  <section className="sequence-storage"><Database size={19}/><div><strong>Persistent variable-length context index</strong><p>{index?.file||'data/ft-sequences.sqlite'} · compact two-byte score tokens · per-season incremental updates · no current-fixture recommendations</p><small>{index?`${num(index.observed_patterns)} observed contexts · ${index.seasons} indexed seasons · ${(index.database_bytes/1048576).toFixed(1)} MB`:'The updated collector builds this separate SQLite index from the existing real archive.'}</small></div>{isOnline()&&<a className="button secondary small-button" href="/api/export/sequence-index" download><Download size={13}/>Index database</a>}<Status tone={index?.status==='ready'?'green':'amber'}>{index?.status==='ready'?'INDEXED':index?.status==='indexing'?'INDEXING':'LOCAL ARCHIVE'}</Status></section>
  {help&&<Modal title="Historical evidence, not a correct-score oracle" onClose={()=>setHelp(false)} wide><div className="methodology"><p className="lead">This workspace catalogs recorded FT sequences and the source scores immediately following them. It does not select an upcoming result, estimate betting confidence, or claim precise prediction.</p><h3>How patterns are indexed</h3><p>Every contiguous sequence of lengths 1–30 inside each team-season is considered. Unknown FT slots stop a sequence. If the immediately following FT is known within the same season, that outcome is counted. Terminal or unrecorded next rounds remain unknown.</p><h3>Why not enumerate all theoretical combinations?</h3><p>With {vocabulary.length} observed score values, length L has {vocabulary.length} to the power L theoretical combinations. Most long combinations never occurred. The sparse variable-length index stores every actually observed context and its evidence, not billions of zero-data combinations.</p><h3>Counts and dependence</h3><p>A team-sequence occurrence describes one team's chronological path. Both opponents may create the same context before the same next match. The primary distribution therefore deduplicates following source match IDs. Even after that, overlapping patterns and related records are not independent statistical trials.</p><h3>Small samples are not precision</h3><p>A long pattern often has only one observed continuation. A 1-of-1 historical count does not make the next result certain. These frequencies are never presented as probabilities for an incoming fixture.</p><h3>Algorithms and storage</h3><p>The backend uses compact binary context keys, a variable-length sparse index and per-season incremental aggregation in SQLite. The browser can independently reproduce the query from the loaded real archive, including in the saved HTML. No external football data, invented outcomes, or unvalidated AI forecast is used.</p></div></Modal>}
 </div>;
}
