import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Layers3,ArrowRight,ChevronLeft,Focus,Info,Check,Clock3,LockKeyhole,RefreshCw,Eye,Waypoints,History,HelpCircle} from 'lucide-react';
import {PageHead,TeamBadge,Status,Modal,api,num,pad,dateLabel} from './shared';
import {archiveFor,compareGold} from './model';
import {projectHistoricalRow,trailCondition,consecutiveClosed} from './trailModel';
import {Alignment} from './Comparator';
import {CorrectScoreCard} from './Gold';

const empty=()=>Array.from({length:30},(_,i)=>({day:i+1,ft:null,code:null,match_id:null}));
function TrailScore({card,currentDay,history=false,captured=false,broken=false,onInspect}){
 const ft=card?.ft;
 return <button className={`trail-score ${ft!=null?'known':'unknown'} ${history?'historical':'current'} ${captured?'captured':''} ${broken?'broken':''}`} disabled={!card?.match_id} onClick={()=>card?.match_id&&onInspect(card.match_id)} data-current-day={currentDay} data-historical-day={history?card?.day:undefined} data-score={ft||''} data-captured={captured?'true':'false'} title={card?`${history?'Historical':'Current'} MD${card.day} · FT ${ft||'not recorded'}${history?` · aligned under current MD${currentDay}`:''}`:'Historical day outside this current-season canvas'}><small>{history?'H':'MD'}{pad(card?.day||currentDay)}</small><strong>{ft||'—'}</strong>{captured&&<i/>}{broken&&<b>×</b>}</button>;
}

export default function Trail({workspace,data,mode,initialTeam='',initialScope='all',onInspect,onRefresh,toast}){
 const rows=workspace.single_hit_rows||[],tracker=workspace.single_hit_tracker||{};
 const incomingSeason=data.current_season;
 // Keep the ending season visible while its MD30 is genuinely still playing.
 const ending=data.ongoing?.season!==incomingSeason&&data.ongoing?.matches?.some(m=>m.status==='live')?data.ongoing.season:null;
 const activeSeason=ending||incomingSeason;
 const [scope,setScope]=useState(initialScope);
 const latestRetained=[...rows].filter(r=>r.scope===scope).sort((a,b)=>b.current_season-a.current_season)[0]?.current_season;
 const automaticSeason=rows.some(r=>r.current_season===activeSeason&&r.scope===scope)?activeSeason:latestRetained||activeSeason;
 const [seasonChoice,setSeasonChoice]=useState(initialTeam?'current':'auto');
 const season=seasonChoice==='current'?activeSeason:seasonChoice==='auto'?automaticSeason:Number(seasonChoice);
 const [team,setTeam]=useState(initialTeam||rows.find(r=>r.current_season===season&&r.scope===initialScope)?.current_team||workspace.roster[0]?.team||''),[inspectRow,setInspectRow]=useState(null),[help,setHelp]=useState(false),[syncing,setSyncing]=useState(false);
 const archive=useMemo(()=>archiveFor(workspace),[workspace.archive_id,workspace.results_revision,workspace.results.length]);
 const seasons=[...new Set([activeSeason,...rows.map(r=>r.current_season)])].filter(Boolean).sort((a,b)=>b-a);
 const names=[...new Set([...(season===incomingSeason?workspace.roster.map(r=>r.team):[]),...(archive.get(season)?.keys()||[]),...rows.filter(r=>r.current_season===season).map(r=>r.current_team)])].sort();
 const chosen=names.includes(team)?team:names[0]||'';
 const stream=rows.filter(r=>r.current_season===season&&r.current_team===chosen&&r.scope===scope).sort((a,b)=>a.sequence_no-b.sequence_no);
 const rawCurrent=season===incomingSeason?workspace.roster.find(r=>r.team===chosen)?.cards:null;
 const currentCards=rawCurrent||archive.get(season)?.get(chosen)||empty();
 const seasonMeta=data.seasons.find(s=>s.id===season);
 const prefix=season===incomingSeason?data.completed_prefix:consecutiveClosed(seasonMeta);
 const complete=consecutiveClosed(seasonMeta)===30;
 const comparison=useMemo(()=>season===incomingSeason?compareGold(workspace,scope):null,[workspace.archive_id,workspace.results_revision,workspace.results.length,incomingSeason,data.upcoming.day,scope,season]);
 const match=comparison?.teams.find(t=>t.team===chosen);
 const scroll=useRef(null);
 useEffect(()=>{if(initialTeam)setTeam(initialTeam);},[initialTeam]);
 function focus(day){requestAnimationFrame(()=>{const el=scroll.current,card=el?.querySelector(`.trail-current-row [data-current-day="${day}"]`),label=el?.querySelector('.trail-row-label');if(el&&card){const left=card.getBoundingClientRect().left-el.getBoundingClientRect().left+el.scrollLeft;el.scrollLeft=Math.max(0,left-(label?.getBoundingClientRect().width||175)-10);}});}
 useEffect(()=>{focus(stream.length?stream[stream.length-1].current_start:1);},[chosen,season,scope,stream.map(r=>`${r.id}:${r.current_start}:${r.current_end}`).join('|')]);
 async function captureNow(){if(mode!=='live'){toast?.('Saved snapshots display retained trails. Run the live collector to capture new one-match events.','info');return;}setSyncing(true);try{const response=await api('/api/trails/sync',{method:'POST'});await onRefresh?.();toast?.(response.status==='waiting_for_current_backfill'?'Waiting for the current FT prefix to finish catching up.':response.status==='waiting_for_fresh_source'?'Source observations need to refresh before new rows can be captured.':'Single-hit conditions checked. Only exact-count-one changes are saved.');}catch(e){toast?.(e.message,'error');}finally{setSyncing(false);}}
 const waiting=mode!=='live'?'Saved trail snapshot':data.source.stale?'Source delayed · no new captures':complete?'Season complete · retained archive':season!==activeSeason?'Retained earlier-season trail':ending?'Completing the previous season':tracker.status==='waiting_for_first_two_rounds'?'Waiting for MD1 and MD2 to close':tracker.status==='waiting_for_current_backfill'?'Catching up the current prefix':match?.match_count===1?'Exactly 1 · eligible for capture':`Waiting for 1 exact match${match?.ready?` · currently ${match.match_count}`:''}`;
 return <div className="trail-workspace"><PageHead eyebrow="SINGLE-HIT MEMORY / CORRECT SCORES" title="The pieces of a season." description="One fixed current-season row. A lasting trail of the histories that matched it — only when there was exactly one."><button className="button secondary" onClick={()=>setHelp(true)}><HelpCircle size={15}/>How rows are saved</button><button className="button gold-button" onClick={captureNow} disabled={syncing||mode!=='live'}><RefreshCw size={15} className={syncing?'spin':''}/>Check now</button></PageHead>
  <section className="panel trail-controls"><label><span>Current team’s season</span><select value={seasonChoice==='auto'?(season===activeSeason?'current':String(season)):seasonChoice} onChange={e=>setSeasonChoice(e.target.value)} aria-label="Trail season"><option value="current">{activeSeason} · {ending?'finishing season':'current season'}</option>{seasons.filter(s=>s!==activeSeason).map(s=><option key={s} value={s}>{s} · retained trail</option>)}</select></label><label><span>Team</span><select value={chosen} onChange={e=>setTeam(e.target.value)} aria-label="Trail team">{names.map(n=><option key={n} value={n}>{n}</option>)}</select></label><label><span>Uniqueness within</span><select value={scope} onChange={e=>setScope(e.target.value)} aria-label="Trail historical scope"><option value="all">All historical teams</option><option value="same">Same team only</option></select></label><div className="trail-store"><LockKeyhole size={15}/><span>Saved by team + season + scope<small>{mode==='live'?'SQLite · survives restarts':'Retained in this captured archive'}</small></span></div></section>
  <div className="trail-stat-grid"><div><span>Current FT prefix</span><strong>{prefix}<small>/ 30 days</small></strong><p>{chosen||'Selected team'} · season {season}</p></div><div><span>Historical rows retained</span><strong>{stream.length}</strong><p>Old rows are never replaced by a new match.</p></div><div><span>Saved unique observations</span><strong>{num(stream.reduce((n,r)=>n+r.observation_count,0))}</strong><p>A continuing alignment extends its own row.</p></div><div className="trail-single-stat"><span>Exact matches now</span><strong>{season===incomingSeason&&match?.ready?num(match.match_count):'—'}</strong><p>Only the value <b>1</b> allows a historical capture.</p></div></div>
  <div className="trail-capture-status"><Status tone={mode==='live'&&!data.source.stale&&match?.match_count===1?'green':'amber'}>{waiting}</Status><span>{tracker.started_at?`Tracking enabled ${dateLabel(tracker.started_at)}`:'Tracking starts with the updated collector; past one-hit events are not invented.'}</span></div>
  {season!==activeSeason&&complete&&<div className="notice trail-archive-note"><History size={16}/><span>Viewing a completed season’s retained trail. The new season {activeSeason} has its own separate rows; choose “current season” to follow new captures.</span></div>}
  {!tracker.enabled&&<div className="notice warning"><Info size={16}/><span>Your FT records are available, but this snapshot/server predates Single-hit Trail tracking. Update and restart the collector to record new unique matches.</span></div>}
  {tracker.status==='waiting_for_current_backfill'&&mode==='live'&&season===incomingSeason&&<div className="notice warning"><Info size={16}/><span>Current prefix MD{tracker.available_prefix||0} is still being backfilled toward MD{tracker.required_prefix}. Old replayed prefixes are not recorded as new live one-hit events.</span></div>}
  <section className="panel trail-board"><header><div><span className="section-kicker">STATIC MD1–30 CANVAS</span><h2>{chosen||'Current team'} · Single-hit trail</h2><p>Every saved historical row is shifted onto the same current-season day grid.</p></div><div><button className="button secondary small-button" onClick={()=>focus(1)}><ChevronLeft size={13}/>MD1</button><button className="button secondary small-button" disabled={!stream.length} onClick={()=>focus(stream[stream.length-1].current_start)}><Focus size={13}/>Latest capture</button></div></header><div className="trail-legend"><span><i className="trail-key-current"/>Current FT</span><span><i className="trail-key-captured"/>Saved exact-match fragment</span><span><i className="trail-key-context"/>Historical context</span><span><i className="trail-key-break"/>First later difference</span></div>
   <div className="trail-scroll" ref={scroll}><div className="trail-canvas"><div className="trail-grid-row trail-ruler"><div className="trail-row-label">CURRENT MATCHDAY <ArrowRight size={11}/></div>{Array.from({length:30},(_,i)=><span key={i}>{pad(i+1)}</span>)}</div><div className="trail-grid-row trail-current-row"><div className="trail-row-label"><span className="trail-row-kind">ONGOING SEASON · FIXED</span><span className="trail-row-team"><TeamBadge name={chosen} small/><strong>{chosen}</strong></span><small>S{season} · MD1–30</small><span className="trail-row-note">New FT fills its original day.</span></div>{currentCards.map((card,i)=><TrailScore key={i} card={card} currentDay={i+1} onInspect={onInspect}/>)}</div>
    {stream.map((row,index)=>{const condition=trailCondition(row,currentCards,prefix),projected=projectHistoricalRow(row),latest=index===stream.length-1;
     return <div className={`trail-grid-row trail-history-row ${condition.state}`} key={row.id} data-row-id={row.id} data-sequence={row.sequence_no} data-offset={row.alignment_offset}><div className="trail-row-label"><span className="trail-row-kind"><b>{pad(index+1)}</b> UNIQUE MATCH SNAPSHOT</span><span className="trail-row-team"><TeamBadge name={row.historical_team} small/><strong>{row.historical_team}</strong></span><small>S{row.historical_season} · current MD{row.current_start}–{row.current_end}</small><span className={`trail-row-condition ${condition.state}`}>{!latest&&condition.state==='matching'?'Retained · earlier capture':condition.label}</span><button className="trail-inspect" onClick={()=>setInspectRow(row)}><Eye size={10}/>Inspect saved row</button></div>{projected.map(cell=>cell.card?<TrailScore key={cell.currentDay} card={cell.card} currentDay={cell.currentDay} history captured={cell.captured} broken={condition.state==='broken'&&condition.day===cell.currentDay} onInspect={()=>setInspectRow(row)}/>:<div className="trail-outside" key={cell.currentDay} data-current-day={cell.currentDay} title="No historical day at this aligned position"/>)}</div>;
    })}
   </div></div>
   {!stream.length&&<div className="trail-empty"><Waypoints size={28}/><h3>The current season is ready. Its trail starts at one exact match.</h3><p>{mode!=='live'?'This saved file has no retained one-match rows for this team and scope. New captures require the live collector.':'The collector watches all incoming teams. When this team’s count is exactly 1, its historical row is saved here automatically. Counts of 0, 2 or more add nothing.'}</p></div>}
   <footer><span><LockKeyhole size={12}/>Historical scores and offsets are frozen; the current top row continues filling.</span><span>Rows outside current MD1–30 are clipped visually, not deleted. Inspect a row for its full historical blueprint.</span></footer>
  </section>
  {stream.length>0&&<section className="trail-capture-list"><div className="section-head"><div className="section-title"><h2>How this trail was assembled</h2></div><span className="muted-text">Order is capture order, not a ranking</span></div><div>{stream.map((row,i)=><button key={row.id} onClick={()=>setInspectRow(row)}><span className="trail-list-number">{pad(i+1)}</span><div><strong>{row.historical_team} <small>· S{row.historical_season}</small></strong><p>Current MD{row.current_start}–{row.current_end} <ArrowRight size={11}/> Historical MD{row.historical_start}–{row.historical_end}</p></div><span><b>{row.observation_count} one-hit observation{row.observation_count===1?'':'s'}</b><small>{dateLabel(row.first_seen)}</small></span><Eye size={14}/></button>)}</div></section>}
  <div className="notice trail-method-note"><Info size={18}/><span><strong>One means one in the selected archive pool at capture time.</strong> Refreshing the same match does not duplicate it. If an alignment breaks or a different unique alignment appears, its saved row stays and the next fragment gets a new row. Completed seasons remain archived separately. These are historical matches, not future-score predictions.</span></div>
  {inspectRow&&<SavedTrailRow row={inspectRow} onClose={()=>setInspectRow(null)}/>} {help&&<TrailHelp onClose={()=>setHelp(false)}/>}
 </div>;
}

function SavedTrailRow({row,onClose}){
 const observed=row.observations||[],current=row.latest_current_cards.slice(row.current_start-1,row.current_end);
 return <Modal title={`${row.historical_team} · retained single-hit row`} onClose={onClose} wide><div className="saved-trail-intro"><p>Capture <b>{row.sequence_no}</b> for <b>{row.current_team}</b> in season <b>{row.current_season}</b>. Every saved observation below was recorded only when its exact-match count was <b>1</b>.</p><div><span>Pool: {row.scope==='all'?'all historical teams':'same team only'}</span><span>First seen {dateLabel(row.first_seen)}</span><span>Last extended {dateLabel(row.last_seen)}</span></div></div><div className="saved-trail-alignment"><Alignment kind="correct_score" CardComponent={CorrectScoreCard} currentLabel="CAPTURED CURRENT SCORES" currentTeam={row.current_team} currentSeason={row.current_season} cards={current} historicalTeam={row.historical_team} historicalSeason={row.historical_season} historicalCards={row.historical_cards} start={row.historical_start} onInspect={null}/></div><div className="saved-trail-observations"><h3>Unique observations retained</h3>{observed.map(o=><div key={o.observation_key}><Check size={13}/><span><b>1 exact</b> · current MD{o.current_start}–{o.current_end} ↔ history MD{o.historical_start}–{o.historical_end}<small>{o.historical_blueprints} historical blueprints in the search pool · {dateLabel(o.observed_at)}</small></span><code>{o.scores.join(' · ')}</code></div>)}<p>Historical cells beyond the current MD1–30 canvas remain available in the scrollable full blueprint above. This saved row is not overwritten when current results stop matching.</p></div></Modal>;
}
function TrailHelp({onClose}){return <Modal title="Only one. Keep the whole trail." onClose={onClose} wide><div className="methodology"><p className="lead">Single-hit Trail keeps the pieces of historical correct-score patterns that were uniquely aligned with your current team.</p><ol className="gold-rules-list"><li><b>The top stays in place:</b> current MD1–30 always use the same columns. Newly finalized FT scores fill their original positions.</li><li><b>Only exact count 1 can capture:</b> the observer uses the same full-prefix-first Gold search and the selected all-team/same-team pool. Zero or multiple matches never add a historical row.</li><li><b>A continuing piece extends its own row:</b> the same historical team, season and offset must still match without a gap or differing score. Repeated identical refreshes are ignored.</li><li><b>A broken or different piece gets a new row:</b> the old historical scores and alignment stay saved. When another one-match result appears, it is appended underneath.</li><li><b>Every incoming team is watched:</b> recording is done by the running collector, not only while this page is open. Trails are saved separately for each current team, season and scope.</li><li><b>A season ends without losing its trail:</b> its top row can finish MD30 and the captured rows remain available under that season. A new season gets a separate trail.</li></ol><h3>Capture boundaries</h3><p>The source must be fresh and the current FT prefix must be caught up near the playing round. Incomplete old prefixes being backfilled are not replayed as new live signals. Uniqueness refers to the records available in the database at capture time; each observation records that pool size. No past one-hit events are invented when installing the feature.</p><h3>Scores outside the canvas</h3><p>A historical row can start before current MD1 or extend after current MD30 when it is shifted. Those contextual cells are clipped from the fixed view, but all 30 historical cards remain stored and can be inspected.</p><div className="notice"><Info size={18}/><span>Saved HTML displays captured trails but cannot collect new events without a running server. Historical uniqueness is not predictive confidence or a bet recommendation.</span></div></div></Modal>;}
